import { ITicketRepository } from '../../../domain/interfaces/repository.interface';
import { Ticket } from '../../../domain/entities/ticket';
import { TicketInput } from '@shared/schemas/tickets';
import { User } from '../../../domain/entities/user';

export class CreateTicketUseCase {
    constructor(private ticketRepo: ITicketRepository) { }

    async execute(data: TicketInput, user: User): Promise<Ticket> {
        // Prepare Ticket Data
        const now = new Date().toISOString();
        const createdByUserName = `${user.firstName || ''} ${user.lastName || ''}`.trim();

        const ticketData: Ticket = {
            ...data,
            id: '', // Generated by Repo or overwritten
            ticketId: `TKT-${Date.now()}`,
            status: 'NEW',
            type: data.type || 'PROBLEM_SUBMISSION',
            createdByUserId: user.uid,
            createdByUserName,
            // createdByEmail: user.email, // Not in schema
            createdAt: now,
            updatedAt: now,
            comments: [{
                id: crypto.randomUUID(),
                content: `Ticket created by ${createdByUserName} at ${new Date().toLocaleString()}`,
                userId: user.uid,
                createdAt: now
            }]
        };

        const createdTicket = await this.ticketRepo.create(ticketData);
        return createdTicket;
    }
}
