import { createContext, useState, useContext, useEffect, type ReactNode } from 'react';
import { useAuth } from './AuthContext';

export type LanguageCode = 'en' | 'hi' | 'bn' | 'te' | 'mr' | 'ta' | 'ur' | 'gu' | 'kn' | 'ml' | 'pa';

export interface LanguageContextType {
    language: LanguageCode;
    setLanguage: (lang: LanguageCode) => void;
    direction: 'ltr' | 'rtl';
    t: (text: string) => string; // Placeholder for UI strings translation
}

const LANGUAGES: Record<LanguageCode, { name: string; dir: 'ltr' | 'rtl' }> = {
    'en': { name: 'English', dir: 'ltr' },
    'hi': { name: 'Hindi', dir: 'ltr' },
    'bn': { name: 'Bengali', dir: 'ltr' },
    'te': { name: 'Telugu', dir: 'ltr' },
    'mr': { name: 'Marathi', dir: 'ltr' },
    'ta': { name: 'Tamil', dir: 'ltr' },
    'ur': { name: 'Urdu', dir: 'rtl' },
    'gu': { name: 'Gujarati', dir: 'ltr' },
    'kn': { name: 'Kannada', dir: 'ltr' },
    'ml': { name: 'Malayalam', dir: 'ltr' },
    'pa': { name: 'Punjabi', dir: 'ltr' }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const { user } = useAuth();
    const [language, setLanguageState] = useState<LanguageCode>('en');

    // Initialize from user profile if available, else local storage, else 'en'
    useEffect(() => {
        if (user?.language) {
            setLanguageState(user.language as LanguageCode);
        } else {
            const saved = localStorage.getItem('app_language') as LanguageCode;
            if (saved && LANGUAGES[saved]) {
                setLanguageState(saved);
            }
        }
    }, [user?.language]);

    const setLanguage = (lang: LanguageCode) => {
        setLanguageState(lang);
        localStorage.setItem('app_language', lang);

        // Update user profile if logged in
        // We'll trust the component calling this to trigger the API update or we do it here?
        // Let's do it here for convenience if user is logged in.
        // But we need an API client. For now, we'll just update state and localStorage.
        // The Selector component can handle the API call or we can add it here if we had api client imported.
    };

    const direction = LANGUAGES[language].dir;

    // UI Dictionary
    const DICTIONARY: Record<LanguageCode, Record<string, string>> = {
        'en': {
            'nav.dashboard': 'Dashboard',
            'nav.solutions': 'Solutions',
            'nav.partners': 'Partners',
            'nav.tickets': 'Tickets',
            'nav.users': 'Users',
            'nav.reports': 'Reports',
            'nav.login': 'Login / Register',
            'nav.logout': 'Logout',
            'common.back': 'Back',
            'common.save': 'Save',
            'common.cancel': 'Cancel',
            'common.full_catalog': 'Full Catalog',
            'common.back_to_list': 'Back to List',
            'common.ai_import': 'AI Assisted Import',
            'dashboard.total_solutions': 'Total Solutions',
            'dashboard.active_partners': 'Active Partners',
            'dashboard.my_tickets': 'My Tickets',
            'common.view_all': 'View All',
            'dashboard.quick_actions': 'Quick Actions',
            'dashboard.submit_solution': 'Submit a Solution',
            'dashboard.submit_desc': 'Share your innovative solution with the platform.',
            'dashboard.propose_partner': 'Propose a Partner',
            'dashboard.propose_desc': 'Recommend a new partner organization.',
            'solutions.title': 'Solutions',
            'solutions.submit_new': 'Submit New Solution',
            'solutions.details': 'Solution Details',
            'partners.title': 'Partners',
            'partners.propose_new': 'Propose New Partner',
            'partners.details': 'Partner Details',
            'tickets.title': 'Tickets',
            'tickets.submit_new': 'Submit New Ticket',
            'tickets.details': 'Ticket Details',
            'tickets.approve_request': 'Approve Request',
            'reports.title': 'Solutions Report',
            'reports.back_to_solutions': 'Back to Solutions',
            'reports.status_filter': 'Solution Status',
            'reports.by_domain': 'Solutions by Domain',
            'reports.by_provider': 'Solutions by Provider',
            'reports.found': 'Solutions Found',
            'reports.no_match': 'No solutions match the selected criteria.',
            'list.view_action': 'View',
            'list.column_name': 'Name',
            'list.column_domain': 'Domain',
            'list.column_status': 'Status',
            'list.column_org': 'Organization',
            'list.column_type': 'Type',
            'list.column_proposed_by': 'Proposed By',
            'list.column_title': 'Title',
            'list.toggle_list': 'List',
            'list.toggle_ai': 'AI Assistant',
            'list.search_placeholder': 'Search...',
            'list.go': 'Go',
            'list.create_new': 'Create New',
            'list.page_label': 'Page',
            // Enums
            'domain.Water': 'Water',
            'domain.Health': 'Health',
            'domain.Energy': 'Energy',
            'domain.Education': 'Education',
            'domain.Livelihood': 'Livelihood',
            'domain.Sustainability': 'Sustainability',
            'status.PROPOSED': 'PROPOSED',
            'status.DRAFT': 'DRAFT',
            'status.PENDING': 'PENDING',
            'status.APPROVED': 'APPROVED',
            'status.MATURE': 'MATURE',
            'status.PILOT': 'PILOT',
            'status.REJECTED': 'REJECTED',
            'status.NEW': 'NEW',
            'status.IN_PROGRESS': 'IN_PROGRESS',
            'status.RESOLVED': 'RESOLVED',
            'status.CLOSED': 'CLOSED',
            // Partner Entity Types
            'entity_type.NGO': 'NGO',
            'entity_type.Social Impact Entity': 'Social Impact Entity',
            'entity_type.Academic': 'Academic',
            'entity_type.Corporate': 'Corporate',
            // Form Titles & Labels (Explicit mapping, though redundant if key==value, useful for strict t())
            'System Info': 'System Info',
            'Solution Overview': 'Solution Overview',
            'Impact & Benefits': 'Impact & Benefits',
            'Implementation Details': 'Implementation Details',
            'Resources': 'Resources',
            'Attachments': 'Attachments',
            'ID': 'ID',
            'Created At': 'Created At',
            'Updated At': 'Updated At',
            'Solution Name': 'Solution Name',
            'Summary (One Line)': 'Summary (One Line)',
            'Detailed Description': 'Detailed Description',
            'Domain': 'Domain',
            'Vertical Domain': 'Vertical Domain',
            'Unique Value Proposition (Benefit)': 'Unique Value Proposition (Benefit)',
            'Cost and Effort': 'Cost and Effort',
            'Return on Investment (ROI)': 'Return on Investment (ROI)',
            'Launch Year': 'Launch Year',
            'Target Beneficiaries': 'Target Beneficiaries',
            'References (Links)': 'References (Links)',
            'Status': 'Status',
            'Provided By Partner ID': 'Provided By Partner ID',
            'Provided By Partner Name': 'Provided By Partner Name',
            'Proposed By User ID': 'Proposed By User ID',
            'Proposed By User Name': 'Proposed By User Name',
            // Partner Form Labels
            'Organization Details': 'Organization Details',
            'Contact Details': 'Contact Details',
            'Location': 'Location',
            'Organization Name': 'Organization Name',
            'Entity Type': 'Entity Type',
            'Website URL': 'Website URL',
            'Contact Information': 'Contact Information',
            'Address': 'Address',
            'Email': 'Email',
            'Phone': 'Phone',
            'City': 'City',
            'Country': 'Country',
            'Proposer ID': 'Proposer ID',
            'Proposed By': 'Proposed By'
        },
        'hi': {
            'nav.dashboard': 'डैशबोर्ड',
            'nav.solutions': 'समाधान',
            'nav.partners': 'साझेदार',
            'nav.tickets': 'टिकट',
            'nav.users': 'उपयोगकर्ता',
            'nav.reports': 'रिपोर्ट',
            'nav.login': 'लॉग इन / रजिस्टर',
            'nav.logout': 'लॉग आउट',
            'common.back': 'वापस',
            'common.save': 'सहेजें',
            'common.cancel': 'रद्द करें',
            'common.full_catalog': 'पूर्ण सूची',
            'common.back_to_list': 'सूची पर वापस जाएं',
            'common.ai_import': 'एआई सहायता प्राप्त आयात',
            'dashboard.total_solutions': 'कुल समाधान',
            'dashboard.active_partners': 'सक्रिय साझेदार',
            'dashboard.my_tickets': 'मेरे टिकट',
            'common.view_all': 'सभी देखें',
            'dashboard.quick_actions': 'त्वरित कार्रवाई',
            'dashboard.submit_solution': 'एक समाधान जमा करें',
            'dashboard.submit_desc': 'मंच के साथ अपना विचार साझा करें।',
            'dashboard.propose_partner': 'एक साथी प्रस्तावित करें',
            'dashboard.propose_desc': 'एक नए भागीदार संगठन की सिफारिश करें।',
            'solutions.title': 'समाधान',
            'solutions.submit_new': 'नया समाधान जमा करें',
            'solutions.details': 'समाधान विवरण',
            'partners.title': 'साझेदार',
            'partners.propose_new': 'नया साथी प्रस्तावित करें',
            'partners.details': 'साझेदार विवरण',
            'tickets.title': 'टिकट',
            'tickets.submit_new': 'नया टिकट जमा करें',
            'tickets.details': 'टिकट विवरण',
            'tickets.approve_request': 'अनुरोध स्वीकार करें',
            'reports.title': 'समाधान रिपोर्ट',
            'reports.back_to_solutions': 'समाधान पर वापस',
            'reports.status_filter': 'समाधान स्थिति',
            'reports.by_domain': 'डोमेन द्वारा समाधान',
            'reports.by_provider': 'प्रदाता द्वारा समाधान',
            'reports.found': 'समाधान मिले',
            'reports.no_match': 'चयनित मानदंड से कोई समाधान मेल नहीं खाता।',
            'list.view_action': 'देखें',
            'list.column_name': 'नाम',
            'list.column_domain': 'डोमेन',
            'list.column_status': 'स्थिति',
            'list.column_org': 'संगठन',
            'list.column_type': 'प्रकार',
            'list.column_proposed_by': 'प्रस्तावित द्वारा',
            'list.column_title': 'शीर्षक',
            'list.toggle_list': 'सूची',
            'list.toggle_ai': 'एआई सहायक',
            'list.search_placeholder': 'खोजें...',
            'list.go': 'जाएं',
            'list.create_new': 'नया बनाएँ',
            'list.page_label': 'पृष्ठ',
            // Enums
            'domain.Water': 'जल',
            'domain.Health': 'स्वास्थ्य',
            'domain.Energy': 'ऊर्जा',
            'domain.Education': 'शिक्षा',
            'domain.Livelihood': 'आजीविका',
            'domain.Sustainability': 'स्थिरता',
            'status.PROPOSED': 'प्रस्तावित',
            'status.DRAFT': 'मसौदा',
            'status.PENDING': 'लंबित',
            'status.APPROVED': 'स्वीकृत',
            'status.MATURE': 'परिपक्व',
            'status.PILOT': 'पायलट',
            'status.REJECTED': 'अस्वीकृत',
            'status.NEW': 'नया',
            'status.IN_PROGRESS': 'प्रगति पर',
            'status.RESOLVED': 'सुलझाया हुआ',
            'status.CLOSED': 'बंद',
            // Partner Entity Types
            'entity_type.NGO': 'एनजीओ (NGO)',
            'entity_type.Social Impact Entity': 'सामाजिक प्रभाव इकाई',
            'entity_type.Academic': 'अकादमिक',
            'entity_type.Corporate': 'कॉर्पोरेट',
            // Form Titles & Labels
            'System Info': 'सिस्टम जानकारी',
            'Solution Overview': 'समाधान अवलोकन',
            'Impact & Benefits': 'प्रभाव और लाभ',
            'Implementation Details': 'कार्यान्वयन विवरण',
            'Resources': 'संसाधन',
            'Attachments': 'संलग्नक',
            'ID': 'आईडी',
            'Created At': 'बनाया गया',
            'Updated At': 'अद्यतित',
            'Solution Name': 'समाधान का नाम',
            'Summary (One Line)': 'सारांश (एक पंक्ति)',
            'Detailed Description': 'विस्तृत विवरण',
            'Domain': 'डोमेन',
            'Vertical Domain': 'लंबवत डोमेन (Vertical Domain)',
            'Unique Value Proposition (Benefit)': 'अद्वितीय मूल्य प्रस्ताव (लाभ)',
            'Cost and Effort': 'लागत और प्रयास',
            'Return on Investment (ROI)': 'निवेश पर वापसी (ROI)',
            'Launch Year': 'लॉन्च वर्ष',
            'Target Beneficiaries': 'लक्षित लाभार्थी',
            'References (Links)': 'संदर्भ (लिंक)',
            'Status': 'स्थिति',
            'Provided By Partner ID': 'साझेदार आईडी द्वारा प्रदान किया गया',
            'Provided By Partner Name': 'साझेदार नाम द्वारा प्रदान किया गया',
            'Proposed By User ID': 'प्रस्तावित उपयोगकर्ता आईडी',
            'Proposed By User Name': 'प्रस्तावित उपयोगकर्ता नाम',
            // Partner Form Labels
            'Organization Details': 'संगठन विवरण',
            'Contact Details': 'संपर्क विवरण',
            'Location': 'स्थान',
            'Organization Name': 'संगठन का नाम',
            'Entity Type': 'इकाई का प्रकार',
            'Website URL': 'वेबसाइट यूआरएल',
            'Contact Information': 'संपर्क जानकारी',
            'Address': 'पता',
            'Email': 'ईमेल',
            'Phone': 'फ़ोन',
            'City': 'शहर',
            'Country': 'देश',
            'Proposer ID': 'प्रस्तावक आईडी',
            'Proposed By': 'द्वारा प्रस्तावित'
        },
        'bn': {
            'nav.dashboard': 'ড্যাশবোর্ড',
            'nav.solutions': 'সমাধান',
            'nav.partners': 'অংশীদার',
            'nav.tickets': 'টিকেট',
            'nav.users': 'ব্যবহারকারী',
            'nav.reports': 'রিপোর্ট',
            'nav.login': 'লগইন / রেজিস্টার',
            'nav.logout': 'লগআউট',
            'common.back': 'ফিরে যান',
            'common.save': 'সংরক্ষণ',
            'common.cancel': 'বাতিল',
            'common.full_catalog': 'সম্পূর্ণ ক্যাটালগ',
            'common.back_to_list': 'তালিকায় ফিরে যান',
            'common.ai_import': 'AI সহায়তা আমদানি',
            'dashboard.total_solutions': 'মোট সমাধান',
            'dashboard.active_partners': 'সক্রিয় অংশীদার',
            'dashboard.my_tickets': 'আমার টিকেট',
            'common.view_all': 'সব দেখুন',
            'dashboard.quick_actions': 'দ্রুত পদক্ষেপ',
            'dashboard.submit_solution': 'একটি সমাধান জমা দিন',
            'dashboard.submit_desc': 'প্ল্যাটফর্মের সাথে আপনার উদ্ভাবনী সমাধান শেয়ার করুন।',
            'dashboard.propose_partner': 'নতুন অংশীদার প্রস্তাব করুন',
            'dashboard.propose_desc': 'একটি নতুন অংশীদার সংস্থার সুপারিশ করুন।',
            'solutions.title': 'সমাধান',
            'solutions.submit_new': 'নতুন সমাধান জমা দিন',
            'solutions.details': 'সমাধানের বিবরণ',
            'partners.title': 'অংশীদার',
            'partners.propose_new': 'নতুন অংশীদার প্রস্তাব করুন',
            'partners.details': 'অংশীদার বিবরণ',
            'tickets.title': 'টিকেট',
            'tickets.submit_new': 'নতুন টিকেট জমা দিন',
            'tickets.details': 'টিকেট বিবরণ',
            'tickets.approve_request': 'অনুরোধ অনুমোদন করুন',
            'reports.title': 'সমাধান রিপোর্ট',
            'reports.back_to_solutions': 'সমাধানে ফিরে যান',
            'reports.status_filter': 'সমাধানের স্থিতি',
            'reports.by_domain': 'ডোমেইন অনুযায়ী সমাধান',
            'reports.by_provider': 'প্রদানকারী অনুযায়ী সমাধান',
            'reports.found': 'সমাধান পাওয়া গেছে',
            'reports.no_match': 'নির্বাচিত মানদণ্ডের সাথে কোন সমাধান মিলছে না।',
            'list.view_action': 'দেখুন',
            'list.column_name': 'নাম',
            'list.column_domain': 'ডোমেইন',
            'list.column_status': 'স্থিতি',
            'list.column_org': 'সংস্থা',
            'list.column_type': 'ধরণ',
            'list.column_proposed_by': 'প্রস্তাবিত',
            'list.column_title': 'শিরোনাম',
            'list.toggle_list': 'তালিকা',
            'list.toggle_ai': 'AI সহকারী',
            'list.search_placeholder': 'অনুসন্ধান...',
            'list.go': 'যান',
            'list.create_new': 'নতুন তৈরি করুন',
            'list.page_label': 'পৃষ্ঠা',
            // Enums
            'domain.Water': 'জল',
            'domain.Health': 'স্বাস্থ্য',
            'domain.Energy': 'শক্তি',
            'domain.Education': 'শিক্ষা',
            'domain.Livelihood': 'জীবিকা',
            'domain.Sustainability': 'স্থায়িত্ব',
            'status.PROPOSED': 'প্রস্তাবিত',
            'status.DRAFT': 'খসড়া',
            'status.PENDING': 'অপেক্ষমান',
            'status.APPROVED': 'অনুমোদিত',
            'status.MATURE': 'পরিপক্ক',
            'status.PILOT': 'পাইলট',
            'status.REJECTED': 'প্রত্যাখ্যাত',
            'status.NEW': 'নতুন',
            'status.IN_PROGRESS': 'চলমান',
            'status.RESOLVED': 'মীমাংসিত',
            'status.CLOSED': 'বন্ধ',
            // Partner Entity Types
            'entity_type.NGO': 'এনজিও',
            'entity_type.Social Impact Entity': 'সামাজিক প্রভাব সংস্থা',
            'entity_type.Academic': 'একাডেমিক',
            'entity_type.Corporate': 'কর্পোরেট',
            // Form Titles & Labels
            'System Info': 'সিস্টেম তথ্য',
            'Solution Overview': 'সমাধানের ওভারভিউ',
            'Impact & Benefits': 'প্রভাব এবং সুবিধা',
            'Implementation Details': 'বাস্তবায়নের বিবরণ',
            'Resources': 'সম্পদ',
            'Attachments': 'সংলগ্নি',
            'ID': 'আইডি',
            'Created At': 'তৈরি হয়েছে',
            'Updated At': 'আপডেট হয়েছে',
            'Solution Name': 'সমাধানের নাম',
            'Summary (One Line)': 'সারসংক্ষেপ (এক লাইন)',
            'Detailed Description': 'বিস্তারিত বিবরণ',
            'Domain': 'ডোমেইন',
            'Vertical Domain': 'উল্লম্ব ডোমেইন',
            'Unique Value Proposition (Benefit)': 'অনন্য মূল্য প্রস্তাব (সুবিধা)',
            'Cost and Effort': 'খরচ এবং প্রচেষ্টা',
            'Return on Investment (ROI)': 'বিনিয়োগের উপর আয় (ROI)',
            'Launch Year': 'লঞ্চের বছর',
            'Target Beneficiaries': 'লক্ষ্য সুবিধাভোগী',
            'References (Links)': 'রেফারেন্স (লিঙ্ক)',
            'Status': 'স্থিতি',
            'Provided By Partner ID': 'অংশীদার আইডি দ্বারা প্রদান করা হয়েছে',
            'Provided By Partner Name': 'অংশীদার নাম দ্বারা প্রদান করা হয়েছে',
            'Proposed By User ID': 'প্রস্তাবিত ব্যবহারকারী আইডি',
            'Proposed By User Name': 'প্রস্তাবিত ব্যবহারকারী নাম',
            // Partner Form Labels
            'Organization Details': 'সংগঠনের বিবরণ',
            'Contact Details': 'যোগাযোগের বিবরণ',
            'Location': 'অবস্থান',
            'Organization Name': 'প্রতিষ্ঠানের নাম',
            'Entity Type': 'সংস্থার ধরন',
            'Website URL': 'ওয়েবসাইট URL',
            'Contact Information': 'যোগাযোগের তথ্য',
            'Address': 'ঠিকানা',
            'Email': 'ইমেল',
            'Phone': 'ফোন',
            'City': 'শহর',
            'Country': 'দেশ',
            'Proposer ID': 'প্রস্তাবক আইডি',
            'Proposed By': 'প্রস্তাবিত'
        },
        'te': {
            'nav.dashboard': 'డాష్‌బోర్డ్',
            'nav.solutions': 'పరిష్కారాలు',
            'nav.partners': 'భాగస్వామ్యులు',
            'nav.tickets': 'టిక్కెట్లు',
            'nav.users': 'వినియోగదారులు',
            'nav.reports': 'నివేదికలు',
            'nav.login': 'లాగిన్ / నమోదు',
            'nav.logout': 'లాగ్ అవుట్',
            'common.back': 'వెనుకకు',
            'common.save': 'సేవ్ చేయండి',
            'common.cancel': 'రద్దు చేయండి',
            'common.full_catalog': 'పూర్తి జాబితా',
            'common.back_to_list': 'జాబితాకు తిరిగి వెళ్ళు',
            'common.ai_import': 'AI సహాయక దిగుమతి',
            'dashboard.total_solutions': 'మొత్తం పరిష్కారాలు',
            'dashboard.active_partners': 'క్రియాశీల భాగస్వాములు',
            'dashboard.my_tickets': 'నా టిక్కెట్లు',
            'common.view_all': 'అన్నీ చూడండి',
            'dashboard.quick_actions': 'త్వరిత చర్యలు',
            'dashboard.submit_solution': 'పరిష్కారాన్ని సమర్పించండి',
            'dashboard.submit_desc': 'మీ వినూత్న పరిష్కారాన్ని ప్లాట్‌ఫారమ్‌తో పంచుకోండి.',
            'dashboard.propose_partner': 'భాగస్వామిని ప్రతిపాదించండి',
            'dashboard.propose_desc': 'కొత్త భాగస్వామి సంస్థను సిఫార్సు చేయండి.',
            'solutions.title': 'పరిష్కారాలు',
            'solutions.submit_new': 'కొత్త పరిష్కారాన్ని సమర్పించండి',
            'solutions.details': 'పరిష్ార వివరాలు',
            'partners.title': 'భాగస్వామ్యులు',
            'partners.propose_new': 'కొత్త భాగస్వామిని ప్రతిపాదించండి',
            'partners.details': 'భాగస్వామి వివరాలు',
            'tickets.title': 'టిక్కెట్లు',
            'tickets.submit_new': 'కొత్త టికెట్ సమర్పించండి',
            'tickets.details': 'టికెట్ వివరాలు',
            'tickets.approve_request': 'అభ్యర్థనను ఆమోదించండి',
            'reports.title': 'పరిష్కార నివేదిక',
            'reports.back_to_solutions': 'పరిష్కారాలకు తిరిగి వెళ్ళు',
            'reports.status_filter': 'పరిష్ార స్థితి',
            'reports.by_domain': 'డొమైన్ వారీగా పరిష్కారాలు',
            'reports.by_provider': 'ప్రొవైడర్ వారీగా పరిష్కారాలు',
            'reports.found': 'పరిష్కారాలు కనుగొనబడ్డాయి',
            'reports.no_match': 'ఎంచుకున్న ప్రమాణాలకు సరిపోలే పరిష్కారాలు లేవు.',
            'list.view_action': 'చూడండి',
            'list.column_name': 'పేరు',
            'list.column_domain': 'డొమైన్',
            'list.column_status': 'స్థితి',
            'list.column_org': 'సంస్థ',
            'list.column_type': 'రకం',
            'list.column_proposed_by': 'ప్రతిపాదించిన వారు',
            'list.column_title': 'శీర్షిక',
            'list.toggle_list': 'జాబితా',
            'list.toggle_ai': 'AI అసిస్టెంట్',
            'list.search_placeholder': 'శోధించండి...',
            'list.go': 'వెళ్ళండి',
            'list.create_new': 'కొత్తది సృష్టించండి',
            'list.page_label': 'పేజీ',
            // Enums
            'domain.Water': 'నీరు',
            'domain.Health': 'ఆరోగ్యం',
            'domain.Energy': 'శక్తి',
            'domain.Education': 'విద్య',
            'domain.Livelihood': 'జీవనోపాధి',
            'domain.Sustainability': 'సుస్థిరత',
            'status.PROPOSED': 'ప్రతిపాదించబడింది',
            'status.DRAFT': 'చిత్తుప్రతి',
            'status.PENDING': 'పెండింగ్‌లో ఉంది',
            'status.APPROVED': 'ఆమోదించబడింది',
            'status.MATURE': 'పరిపక్వ',
            'status.PILOT': 'పైలట్',
            'status.REJECTED': 'తిరస్కరించబడింది',
            'status.NEW': 'కొత్త',
            'status.IN_PROGRESS': 'పురోగతిలో ఉంది',
            'status.RESOLVED': 'పరిష్కరించబడింది',
            'status.CLOSED': 'మూసివేయబడింది',
            // Partner Entity Types
            'entity_type.NGO': 'NGO',
            'entity_type.Social Impact Entity': 'సామాజిక ప్రభావ సంస్థ',
            'entity_type.Academic': 'అకాడమిక్',
            'entity_type.Corporate': 'కార్పొరేట్',
            // Form Labels
            'System Info': 'సిస్టమ్ సమాచారం',
            'Solution Overview': 'పరిష్ార అవలోకనం',
            'Impact & Benefits': 'ప్రభావం & ప్రయోజనాలు',
            'Implementation Details': 'అమలు వివరాలు',
            'Resources': 'వనరులు',
            'Attachments': 'జోడింపులు',
            'ID': 'ID',
            'Created At': 'సృష్టించబడింది',
            'Updated At': 'నవీకరించబడింది',
            'Solution Name': 'పరిష్కారం పేరు',
            'Summary (One Line)': 'సారాంశం (ఒక లైన్)',
            'Detailed Description': 'వివరణాత్మక వివరణ',
            'Domain': 'డొమైన్',
            'Vertical Domain': 'నిలువు డొమైన్',
            'Unique Value Proposition (Benefit)': 'ప్రత్యేక విలువ ప్రతిపాదన (ప్రయోజనం)',
            'Cost and Effort': 'ఖర్చు మరియు కృషి',
            'Return on Investment (ROI)': 'పెట్టుబడిపై రాబడి (ROI)',
            'Launch Year': 'ప్రారంభ సంవత్సరం',
            'Target Beneficiaries': 'లక్ష్య లబ్ధిదారులు',
            'References (Links)': 'సూచనలు (లింక్లు)',
            'Status': 'స్థితి',
            'Provided By Partner ID': 'భాగస్వామి ID ద్వారా అందించబడింది',
            'Provided By Partner Name': 'భాగస్వామి పేరు ద్వారా అందించబడింది',
            'Proposed By User ID': 'ప్రతిపాదిత వినియోగదారు ID',
            'Proposed By User Name': 'ప్రతిపాదిత వినియోగదారు పేరు',
            // Partner Form Labels
            'Organization Details': 'సంస్థ వివరాలు',
            'Contact Details': 'సంప్రదింపు వివరాలు',
            'Location': 'స్థానం',
            'Organization Name': 'సంస్థ పేరు',
            'Entity Type': 'సంస్థ రకం',
            'Website URL': 'వెబ్‌సైట్ URL',
            'Contact Information': 'సంప్రదింపు సమాచారం',
            'Address': 'చిరునామా',
            'Email': 'ఇమెయిల్',
            'Phone': 'ఫోన్',
            'City': 'నగరం',
            'Country': 'దేశం',
            'Proposer ID': 'ప్రతిపాదకుడి ID',
            'Proposed By': 'ద్వారా ప్రతిపాదించబడింది'
        },
        'mr': {
            'nav.dashboard': 'डॅशबोर्ड',
            'nav.solutions': 'उपाय',
            'nav.partners': 'भागीदार',
            'nav.tickets': 'तिकिटे',
            'nav.users': 'वापरकर्ते',
            'nav.reports': 'अहवाल',
            'nav.login': 'लॉगिन / नोंदणी',
            'nav.logout': 'बाहेर पडणे',
            'common.back': 'मागे',
            'common.save': 'जतन करा',
            'common.cancel': 'रद्द करा',
            'common.full_catalog': 'पूर्ण कॅटलॉग',
            'common.back_to_list': 'यादीवर परत जा',
            'common.ai_import': 'AI सहाय्यित आयात',
            'dashboard.total_solutions': 'एकूण उपाय',
            'dashboard.active_partners': 'सक्रिय भागीदार',
            'dashboard.my_tickets': 'माझी तिकिटे',
            'common.view_all': 'सर्व पहा',
            'dashboard.quick_actions': 'त्वरित क्रिया',
            'dashboard.submit_solution': 'उपाय सादर करा',
            'dashboard.submit_desc': 'प्लॅटफॉर्मवर आपली अभिनव कल्पना शेअर करा.',
            'dashboard.propose_partner': 'भागीदार सुचवा',
            'dashboard.propose_desc': 'नवीन भागीदार संस्थेची शिफारस करा.',
            'solutions.title': 'उपाय',
            'solutions.submit_new': 'नवीन उपाय सादर करा',
            'solutions.details': 'उपाय तपशील',
            'partners.title': 'भागीदार',
            'partners.propose_new': 'नवीन भागीदार सुचवा',
            'partners.details': 'भागीदार तपशील',
            'tickets.title': 'तिकिटे',
            'tickets.submit_new': 'नवीन तिकीट सादर करा',
            'tickets.details': 'तिकीट तपशील',
            'tickets.approve_request': 'विनंती मंजूर करा',
            'reports.title': 'उपाय अहवाल',
            'reports.back_to_solutions': 'उपायांवर परत जा',
            'reports.status_filter': 'उपाय स्थिती',
            'reports.by_domain': 'डोमेननुसार उपाय',
            'reports.by_provider': 'प्रदात्यानुसार उपाय',
            'reports.found': 'उपाय सापडले',
            'reports.no_match': 'निवडलेल्या निकषांशी जुळणारे कोणतेही उपाय नाहीत.',
            'list.view_action': 'पहा',
            'list.column_name': 'नाव',
            'list.column_domain': 'डोमेन',
            'list.column_status': 'स्थिती',
            'list.column_org': 'संस्था',
            'list.column_type': 'प्रकार',
            'list.column_proposed_by': 'प्रस्तावित',
            'list.column_title': 'शीर्षक',
            'list.toggle_list': 'यादी',
            'list.toggle_ai': 'AI सहाय्यक',
            'list.search_placeholder': 'शोधा...',
            'list.go': 'जा',
            'list.create_new': 'नवीन तयार करा',
            'list.page_label': 'पृष्ठ',
            // Enums
            'domain.Water': 'पाणी',
            'domain.Health': 'आरोग्य',
            'domain.Energy': 'ऊर्जा',
            'domain.Education': 'शिक्षण',
            'domain.Livelihood': 'उपजीविका',
            'domain.Sustainability': 'शाश्वतता',
            'status.PROPOSED': 'प्रस्तावित',
            'status.DRAFT': 'मसुदा',
            'status.PENDING': 'प्रलंबित',
            'status.APPROVED': 'मंजूर',
            'status.MATURE': 'परिपक्व',
            'status.PILOT': 'पायलट',
            'status.REJECTED': 'नाकारले',
            'status.NEW': 'नवीन',
            'status.IN_PROGRESS': 'प्रगतीपथावर',
            'status.RESOLVED': 'निराकरण झाले',
            'status.CLOSED': 'बंद',
            // Partner Entity Types
            'entity_type.NGO': 'एनजीओ',
            'entity_type.Social Impact Entity': 'सामाजिक प्रभाव संस्था',
            'entity_type.Academic': 'शैक्षणिक',
            'entity_type.Corporate': 'कॉर्पोरेट',
            // Form Titles & Labels
            'System Info': 'सिस्टम माहिती',
            'Solution Overview': 'उपाय विहंगावलोकन',
            'Impact & Benefits': 'प्रभाव आणि फायदे',
            'Implementation Details': 'अंमलबजावणी तपशील',
            'Resources': 'संसाधने',
            'Attachments': 'संलग्नक',
            'ID': 'आयडी',
            'Created At': 'तयार केले',
            'Updated At': 'अद्यतनित केले',
            'Solution Name': 'उपायाचे नाव',
            'Summary (One Line)': 'गोषवारा (एक ओळ)',
            'Detailed Description': 'तपशीलवार वर्णन',
            'Domain': 'डोमेन',
            'Vertical Domain': 'उभा डोमेन',
            'Unique Value Proposition (Benefit)': 'अद्वितीय मूल्य प्रस्ताव (फायदा)',
            'Cost and Effort': 'खर्च आणि प्रयत्न',
            'Return on Investment (ROI)': 'गुंतवणुकीवर परतावा (ROI)',
            'Launch Year': 'लॉन्च वर्ष',
            'Target Beneficiaries': 'लक्ष्य लाभार्थी',
            'References (Links)': 'संदर्भ (लिंक)',
            'Status': 'स्थिती',
            'Provided By Partner ID': 'भागीदार आयडी द्वारे प्रदान',
            'Provided By Partner Name': 'भागीदार नावाद्वारे प्रदान',
            'Proposed By User ID': 'प्रस्तावित वापरकर्ता आयडी',
            'Proposed By User Name': 'प्रस्तावित वापरकर्ता नाव',
            // Partner Form Labels
            'Organization Details': 'संस्थेचा तपशील',
            'Contact Details': 'संपर्क तपशील',
            'Location': 'स्थान',
            'Organization Name': 'संस्थेचे नाव',
            'Entity Type': 'संस्थेचा प्रकार',
            'Website URL': 'वेबसाइट URL',
            'Contact Information': 'संपर्क माहिती',
            'Address': 'पत्ता',
            'Email': 'ईमेल',
            'Phone': 'फोन',
            'City': 'शहर',
            'Country': 'देश',
            'Proposer ID': 'प्रस्तावक आयडी',
            'Proposed By': 'द्वारे प्रस्तावित'
        },
        'ta': {
            'nav.dashboard': 'டாஷ்போர்டு',
            'nav.solutions': 'தீர்வுகள்',
            'nav.partners': 'கூட்டாளர்கள்',
            'nav.tickets': 'டிக்கெட்டுகள்',
            'nav.users': 'பயனர்கள்',
            'nav.reports': 'அறிக்கைகள்',
            'nav.login': 'உள்நுழை / பதிவு',
            'nav.logout': 'வெளியேறு',
            'common.back': 'திரும்ப',
            'common.save': 'சேமி',
            'common.cancel': 'ரத்துசெய்',
            'common.full_catalog': 'முழு பட்டியல்',
            'common.back_to_list': 'பட்டியலுக்குத் திரும்பு',
            'common.ai_import': 'AI உதவி இறக்குமதி',
            'dashboard.total_solutions': 'மொத்த தீர்வுகள்',
            'dashboard.active_partners': 'செயலில் உள்ள கூட்டாளர்கள்',
            'dashboard.my_tickets': 'என் டிக்கெட்டுகள்',
            'common.view_all': 'அனைத்தையும் பார்',
            'dashboard.quick_actions': 'விரைவான நடவடிக்கைகள்',
            'dashboard.submit_solution': 'தீர்வைச் சமர்ப்பிக்கவும்',
            'dashboard.submit_desc': 'உங்கள் புதுமையான தீர்வைப் பகிரவும்.',
            'dashboard.propose_partner': 'கூட்டாளரைப் பரிந்துரைக்கவும்',
            'dashboard.propose_desc': 'புதிய கூட்டாளர் நிறுவனத்தைப் பரிந்துரைக்கவும்.',
            'solutions.title': 'தீர்வுகள்',
            'solutions.submit_new': 'புதிய தீர்வைச் சமர்ப்பிக்கவும்',
            'solutions.details': 'தீர்வு விவரங்கள்',
            'partners.title': 'கூட்டாளர்கள்',
            'partners.propose_new': 'புதிய கூட்டாளரைப் பரிந்துரைக்கவும்',
            'partners.details': 'கூட்டாளர் விவரங்கள்',
            'tickets.title': 'டிக்கெட்டுகள்',
            'tickets.submit_new': 'புதிய டிக்கெட்டைச் சமர்ப்பிக்கவும்',
            'tickets.details': 'டிக்கெட் விவரங்கள்',
            'tickets.approve_request': 'கோரிக்கையை ஏற்கவும்',
            'reports.title': 'தீர்வு அறிக்கை',
            'reports.back_to_solutions': 'திர்வுகளுக்குத் திரும்பு',
            'reports.status_filter': 'தீர்வு நிலை',
            'reports.by_domain': 'களம் வாரியாக தீர்வுகள்',
            'reports.by_provider': 'வழங்குநர் வாரியாக தீர்வுகள்',
            'reports.found': 'தீர்வுகள் காணப்பட்டன',
            'reports.no_match': 'தேர்ந்தெடுக்கப்பட்ட அளவுகோல்களுடன் எந்த தீர்வுகளும் பொருந்தவில்லை.',
            'list.view_action': 'பார்',
            'list.column_name': 'பெயர்',
            'list.column_domain': 'களம்',
            'list.column_status': 'நிலை',
            'list.column_org': 'நிறுவனம்',
            'list.column_type': 'வகை',
            'list.column_proposed_by': 'முன்மொழிந்தவர்',
            'list.column_title': 'தலைப்பு',
            'list.toggle_list': 'பட்டியல்',
            'list.toggle_ai': 'AI உதவியாளர்',
            'list.search_placeholder': 'தேடு...',
            'list.go': 'செல்',
            'list.create_new': 'புதியதை உருவாக்கு',
            'list.page_label': 'பக்கம்',
            // Enums
            'domain.Water': 'நீர்',
            'domain.Health': 'சுகாதாரம்',
            'domain.Energy': 'ஆற்றல்',
            'domain.Education': 'கல்வி',
            'domain.Livelihood': 'வாழ்வாதாரம்',
            'domain.Sustainability': 'நிலைத்தன்மை',
            'status.PROPOSED': 'முன்மொழியப்பட்டது',
            'status.DRAFT': 'வரைவு',
            'status.PENDING': 'நிலுவையில்',
            'status.APPROVED': 'அங்கீகரிக்கப்பட்டது',
            'status.MATURE': 'முதிர்ந்த',
            'status.PILOT': 'பைலட்',
            'status.REJECTED': 'நிராகரிக்கப்பட்டது',
            'status.NEW': 'புதிய',
            'status.IN_PROGRESS': 'செயல்பாட்டில் உள்ளது',
            'status.RESOLVED': 'தீர்க்கப்பட்டது',
            'status.CLOSED': 'மூடப்பட்டது',
            // Partner Entity Types
            'entity_type.NGO': 'தன்னார்வ தொண்டு நிறுவனம்',
            'entity_type.Social Impact Entity': 'சமூக தாக்க நிறுவனம்',
            'entity_type.Academic': 'கல்வி',
            'entity_type.Corporate': 'கார்ப்பரேட்',
            // Form Titles & Labels
            'System Info': 'கணினி தகவல்',
            'Solution Overview': 'தீர்வு கண்ணோட்டம்',
            'Impact & Benefits': 'தாக்கம் & நன்மைகள்',
            'Implementation Details': 'செயல்படுத்தல் விவரங்கள்',
            'Resources': 'வளங்கள்',
            'Attachments': 'இணைப்புகள்',
            'ID': 'ஐடி',
            'Created At': 'உருவாக்கப்பட்டது',
            'Updated At': 'புதுப்பிக்கப்பட்டது',
            'Solution Name': 'தீர்வு பெயர்',
            'Summary (One Line)': 'சுருக்கம் (ஒரு வரி)',
            'Detailed Description': 'விரிவான விளக்கம்',
            'Domain': 'களம்',
            'Vertical Domain': 'செங்குத்து களம்',
            'Unique Value Proposition (Benefit)': 'தனித்துவமான மதிப்பு (நன்மை)',
            'Cost and Effort': 'செலவு மற்றும் முயற்சி',
            'Return on Investment (ROI)': 'முதலீட்டின் மீதான வருவாய் (ROI)',
            'Launch Year': 'தொடங்கப்பட்ட ஆண்டு',
            'Target Beneficiaries': 'இலக்கு பயனாளிகள்',
            'References (Links)': 'குறிப்புகள் (இணைப்புகள்)',
            'Status': 'நிலை',
            'Provided By Partner ID': 'கூட்டாளர் ஐடி மூலம் வழங்கப்பட்டது',
            'Provided By Partner Name': 'கூட்டாளர் பெயரால் வழங்கப்பட்டது',
            'Proposed By User ID': 'முன்மொழியப்பட்ட பயனர் ஐடி',
            'Proposed By User Name': 'முன்மொழியப்பட்ட பயனர் பெயர்',
            // Partner Form Labels
            'Organization Details': 'நிறுவன விவரங்கள்',
            'Contact Details': 'தொடர்பு விவரங்கள்',
            'Location': 'இடம்',
            'Organization Name': 'நிறுவனத்தின் பெயர்',
            'Entity Type': 'நிறுவன வகை',
            'Website URL': 'இணையதள URL',
            'Contact Information': 'தொடர்பு தகவல்',
            'Address': 'முகவரி',
            'Email': 'மின்னஞ்சல்',
            'Phone': 'தொலைபேசி',
            'City': 'நகரம்',
            'Country': 'நாடு',
            'Proposer ID': 'முன்மொழிபவர் ஐடி',
            'Proposed By': 'மூலம் முன்மொழியப்பட்டது'
        },
        'ur': {
            'nav.dashboard': 'ڈیش بورڈ',
            'nav.solutions': 'حل',
            'nav.partners': 'شراکت دار',
            'nav.tickets': 'ٹکٹس',
            'nav.users': 'صارفین',
            'nav.reports': 'رپورٹس',
            'nav.login': 'لاگ ان / رجسٹر',
            'nav.logout': 'لاگ آؤٹ',
            'common.back': 'پیچھے',
            'common.save': 'محفوظ کریں',
            'common.cancel': 'منسوخ کریں',
            'common.full_catalog': 'مکمل فہرست',
            'common.back_to_list': 'فہرست پر واپس جائیں',
            'common.ai_import': 'AI سے معاونت شدہ درآمد',
            'dashboard.total_solutions': 'کل حل',
            'dashboard.active_partners': 'فعال شراکت دار',
            'dashboard.my_tickets': 'میرے ٹکٹ',
            'common.view_all': 'سب دیکھیں',
            'dashboard.quick_actions': 'فوری اقدامات',
            'dashboard.submit_solution': 'نیا حل پیش کریں',
            'dashboard.submit_desc': 'پلیٹ فارم کے ساتھ اپنا جدید حل شیئر کریں۔',
            'dashboard.propose_partner': 'نئے پارٹنر کی تجویز دیں',
            'dashboard.propose_desc': 'نئی پارٹنر تنظیم کی سفارش کریں۔',
            'solutions.title': 'حل',
            'solutions.submit_new': 'نیا حل پیش کریں',
            'solutions.details': 'حل کی تفصیلات',
            'partners.title': 'شراکت دار',
            'partners.propose_new': 'نئے پارٹنر کی تجویز دیں',
            'partners.details': 'شراکت دار کی تفصیلات',
            'tickets.title': 'ٹکٹس',
            'tickets.submit_new': 'نیا ٹکٹ جمع کریں',
            'tickets.details': 'ٹکٹ کی تفصیلات',
            'tickets.approve_request': 'درخواست منظور کریں',
            'reports.title': 'حل کی رپورٹ',
            'reports.back_to_solutions': 'حل پر واپس جائیں',
            'reports.status_filter': 'حل کی حیثیت',
            'reports.by_domain': 'ڈومین کے لحاظ سے حل',
            'reports.by_provider': 'فراہم کنندہ کے لحاظ سے حل',
            'reports.found': 'حل ملے',
            'reports.no_match': 'منتخب کردہ معیار سے کوئی حل مماثل نہیں ہے۔',
            'list.view_action': 'دیکھیں',
            'list.column_name': 'نام',
            'list.column_domain': 'ڈومین',
            'list.column_status': 'حیثیت',
            'list.column_org': 'تنظیم',
            'list.column_type': 'قسم',
            'list.column_proposed_by': 'تجویز کنندہ',
            'list.column_title': 'عنوان',
            'list.toggle_list': 'فہرست',
            'list.toggle_ai': 'AI اسسٹنٹ',
            'list.search_placeholder': 'تلاش کریں...',
            'list.go': 'جائیں',
            'list.create_new': 'نیا بنائیں',
            'list.page_label': 'صفحہ',
            // Enums
            'domain.Water': 'پانی',
            'domain.Health': 'صحت',
            'domain.Energy': 'توانائی',
            'domain.Education': 'تعلیم',
            'domain.Livelihood': 'روزگار',
            'domain.Sustainability': 'پائیداری',
            'status.PROPOSED': 'تجویز کردہ',
            'status.DRAFT': 'مسودہ',
            'status.PENDING': 'زیر التواء',
            'status.APPROVED': 'منظور شدہ',
            'status.MATURE': 'پختہ',
            'status.PILOT': 'پائلٹ',
            'status.REJECTED': 'مسترد',
            'status.NEW': 'نیا',
            'status.IN_PROGRESS': 'جاری ہے',
            'status.RESOLVED': 'حل ہو گیا',
            'status.CLOSED': 'بند',
            // Partner Entity Types
            'entity_type.NGO': 'این جی او',
            'entity_type.Social Impact Entity': 'سوشل امپیکٹ اینٹیٹی',
            'entity_type.Academic': 'تعلیمی',
            'entity_type.Corporate': 'کارپوریٹ',
            // Form Titles & Labels
            'System Info': 'سسٹم کی معلومات',
            'Solution Overview': 'حل کا جائزہ',
            'Impact & Benefits': 'اثرات اور فوائد',
            'Implementation Details': 'عمل درآمد کی تفصیلات',
            'Resources': 'وسائل',
            'Attachments': 'منسلکات',
            'ID': 'آئی ڈی',
            'Created At': 'بنایا گیا',
            'Updated At': 'اپ ڈیٹ کیا گیا',
            'Solution Name': 'حل کا نام',
            'Summary (One Line)': 'خلاصہ (ایک سطر)',
            'Detailed Description': 'تفصیلی وضاحت',
            'Domain': 'ڈومین',
            'Vertical Domain': 'عمودی ڈومین',
            'Unique Value Proposition (Benefit)': 'منفرد قدر کی تجویز (فائدہ)',
            'Cost and Effort': 'لاگت اور کوشش',
            'Return on Investment (ROI)': 'سرمایہ کاری پر واپسی (ROI)',
            'Launch Year': 'لانچ کا سال',
            'Target Beneficiaries': 'ہدف مستحقین',
            'References (Links)': 'حوالہ جات (لنکس)',
            'Status': 'حیثیت',
            'Provided By Partner ID': 'پارٹنر آئی ڈی کے ذریعہ فراہم کردہ',
            'Provided By Partner Name': 'پارٹنر نام کے ذریعہ فراہم کردہ',
            'Proposed By User ID': 'تجویز کنندہ صارف آئی ڈی',
            'Proposed By User Name': 'تجویز کنندہ صارف کا نام',
            // Partner Form Labels
            'Organization Details': 'تنظیم کی تفصیلات',
            'Contact Details': 'رابطہ کی تفصیلات',
            'Location': 'مقام',
            'Organization Name': 'تنظیم کا نام',
            'Entity Type': 'ادارے کی قسم',
            'Website URL': 'ویب سائٹ کا URL',
            'Contact Information': 'رابطہ کی معلومات',
            'Address': 'پتہ',
            'Email': 'ای میل',
            'Phone': 'فون',
            'City': 'شہر',
            'Country': 'ملک',
            'Proposer ID': 'تجویز کنندہ آئی ڈی',
            'Proposed By': 'تجویز کنندہ'
        },
        'gu': {
            'nav.dashboard': 'ડેશબોર્ડ',
            'nav.solutions': 'ઉકેલો',
            'nav.partners': 'ભાગીદારો',
            'nav.tickets': 'ટિકિટ',
            'nav.users': 'વપરાશકર્તાઓ',
            'nav.reports': 'અહેવાલો',
            'nav.login': 'લૉગિન / રજીસ્ટર',
            'nav.logout': 'લૉગ આઉટ',
            'common.back': 'પાછા',
            'common.save': 'સાચવો',
            'common.cancel': 'રદ કરો',
            'common.full_catalog': 'સંપૂર્ણ સૂચિ',
            'common.back_to_list': 'સૂચિ પર પાછા જાઓ',
            'common.ai_import': 'AI સહાયિત આયાત',
            'dashboard.total_solutions': 'કુલ ઉકેલો',
            'dashboard.active_partners': 'સક્રિય ભાગીદારો',
            'dashboard.my_tickets': 'મારી ટિકિટ',
            'common.view_all': 'બધું જુઓ',
            'dashboard.quick_actions': 'ઝડપી ક્રિયાઓ',
            'dashboard.submit_solution': 'ઉકેલ સબમિટ કરો',
            'dashboard.submit_desc': 'પ્લેટફોર્મ સાથે તમારો નવીન વિચાર શેર કરો.',
            'dashboard.propose_partner': 'ભાગીદાર સૂચવો',
            'dashboard.propose_desc': 'નવી ભાગીદાર સંસ્થાની ભલામણ કરો.',
            'solutions.title': 'ઉકેલો',
            'solutions.submit_new': 'નવો ઉકેલ સબમિટ કરો',
            'solutions.details': 'ઉકેલ વિગતો',
            'partners.title': 'ભાગીદારો',
            'partners.propose_new': 'નવા ભાગીદાર સૂચવો',
            'partners.details': 'ભાગીદાર વિગતો',
            'tickets.title': 'ટિકિટ',
            'tickets.submit_new': 'નવી ટિકિટ સબમિટ કરો',
            'tickets.details': 'ટિકિટ વિગતો',
            'tickets.approve_request': 'વિનંતી મંજૂર કરો',
            'reports.title': 'ઉકેલ અહેવાલ',
            'reports.back_to_solutions': 'ઉકેલો પર પાછા જાઓ',
            'reports.status_filter': 'ઉકેલ સ્થિતિ',
            'reports.by_domain': 'ડોમેન દ્વારા ઉકેલો',
            'reports.by_provider': 'પ્રદાતા દ્વારા ઉકેલો',
            'reports.found': 'ઉકેલો મળ્યા',
            'reports.no_match': 'પસંદ કરેલા માપદંડ સાથે કોઈ ઉકેલો મેળ ખાતા નથી.',
            'list.view_action': 'જુઓ',
            'list.column_name': 'નામ',
            'list.column_domain': 'ડોમેન',
            'list.column_status': 'સ્થિતિ',
            'list.column_org': 'સંસ્થા',
            'list.column_type': 'પ્રકાર',
            'list.column_proposed_by': 'સૂચવનાર',
            'list.column_title': 'શીર્ષક',
            'list.toggle_list': 'યાદી',
            'list.toggle_ai': 'AI સહાયક',
            'list.search_placeholder': 'શોધો...',
            'list.go': 'જાઓ',
            'list.create_new': 'નવું બનાવો',
            'list.page_label': 'પૃષ્ઠ',
            // Enums
            'domain.Water': 'પાણી',
            'domain.Health': 'આરોગ્ય',
            'domain.Energy': 'ઊર્જા',
            'domain.Education': 'શિક્ષણ',
            'domain.Livelihood': 'આજીવિકા',
            'domain.Sustainability': 'સ્થિરતા',
            'status.PROPOSED': 'પ્રસ્તાવિત',
            'status.DRAFT': 'ડ્રાફ્ટ',
            'status.PENDING': 'બાકી',
            'status.APPROVED': 'માન્ય',
            'status.MATURE': 'વિકસિત',
            'status.PILOT': 'પાયલોટ',
            'status.REJECTED': 'નકારાયેલ',
            'status.NEW': 'નવું',
            'status.IN_PROGRESS': 'પ્રગતિમાં છે',
            'status.RESOLVED': 'ઉકેલાઈ ગયું',
            'status.CLOSED': 'બંધ',
            // Partner Entity Types
            'entity_type.NGO': 'એનજીઓ',
            'entity_type.Social Impact Entity': 'સામાજિક અસર એકમ',
            'entity_type.Academic': 'શૈક્ષણિક',
            'entity_type.Corporate': 'કોર્પોરેટ',
            // Form Titles & Labels
            'System Info': 'સિસ્ટમ માહિતી',
            'Solution Overview': 'ઉકેલ ઝાંખી',
            'Impact & Benefits': 'અસર અને લાભો',
            'Implementation Details': 'અમલીકરણ વિગતો',
            'Resources': 'સંસાધનો',
            'Attachments': 'જોડાણો',
            'ID': 'આઈડી',
            'Created At': 'બનાવ્યું',
            'Updated At': 'સુધારેલું',
            'Solution Name': 'ઉકેલ નામ',
            'Summary (One Line)': 'સારાંશ (એક લીટી)',
            'Detailed Description': 'વિગતવાર વર્ણન',
            'Domain': 'ડોમેન',
            'Vertical Domain': 'વર્ટિકલ ડોમેન',
            'Unique Value Proposition (Benefit)': 'અનન્ય મૂલ્ય દરખાસ્ત (લાભ)',
            'Cost and Effort': 'ખર્ચ અને પ્રયત્ન',
            'Return on Investment (ROI)': 'રોકાણ પર વળતર (ROI)',
            'Launch Year': 'લોન્ચ વર્ષ',
            'Target Beneficiaries': 'લક્ષ્ય લાભાર્થીઓ',
            'References (Links)': 'સંદર્ભો (લિંક્સ)',
            'Status': 'સ્થિતિ',
            'Provided By Partner ID': 'ભાગીદાર આઈડી દ્વારા પ્રદાન',
            'Provided By Partner Name': 'ભાગીદાર નામ દ્વારા પ્રદાન',
            'Proposed By User ID': 'સૂચવનાર વપરાશકર્તા આઈડી',
            'Proposed By User Name': 'સૂચવનાર વપરાશકર્તા નામ',
            // Partner Form Labels
            'Organization Details': 'સંસ્થા વિગતો',
            'Contact Details': 'સંપર્ક વિગતો',
            'Location': 'સ્થાન',
            'Organization Name': 'સંસ્થાનું નામ',
            'Entity Type': 'એકમ પ્રકાર',
            'Website URL': 'વેબસાઈટ URL',
            'Contact Information': 'સંપર્ક માહિતી',
            'Address': 'સરનામું',
            'Email': 'ઈમેલ',
            'Phone': 'ફોન',
            'City': 'શહેર',
            'Country': 'દેશ',
            'Proposer ID': 'સૂચવનાર આઈડી',
            'Proposed By': 'દ્વારા સૂચવિત'
        },
        'kn': {
            'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
            'nav.solutions': 'ಪರಿಹಾರಗಳು',
            'nav.partners': 'ಪಾಲುದಾರರು',
            'nav.tickets': 'ಟಿಕೆಟ್‌ಗಳು',
            'nav.users': 'ಬಳಕೆದಾರರು',
            'nav.reports': 'ವರದಿಗಳು',
            'nav.login': 'ಲಾಗಿನ್ / ನೋಂದಣಿ',
            'nav.logout': 'ಲಾಗ್ ಔಟ್',
            'common.back': 'ಹಿಂದೆ',
            'common.save': 'ಉಳಿಸಿ',
            'common.cancel': 'ರದ್ದುಮಾಡಿ',
            'common.full_catalog': 'ಪೂರ್ಣ ಪಟ್ಟಿ',
            'common.back_to_list': 'ಪಟ್ಟಿಗೆ ಹಿಂತಿರುಗಿ',
            'common.ai_import': 'AI ನೆರವಿನ ಆಮದು',
            'dashboard.total_solutions': 'ಒಟ್ಟು ಪರಿಹಾರಗಳು',
            'dashboard.active_partners': 'ಸಕ್ರಿಯ ಪಾಲುದಾರರು',
            'dashboard.my_tickets': 'ನನ್ನ ಟಿಕೆಟ್‌ಗಳು',
            'common.view_all': 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
            'dashboard.quick_actions': 'ತ್ವರಿತ ಕ್ರಮಗಳು',
            'dashboard.submit_solution': 'ಪರಿಹಾರವನ್ನು ಸಲ್ಲಿಸಿ',
            'dashboard.submit_desc': 'ವೇದಿಕೆಯೊಂದಿಗೆ ನಿಮ್ಮ ನವೀನ ಪರಿಹಾರವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ.',
            'dashboard.propose_partner': 'ಪಾಲುದಾರನನ್ನು ಪ್ರಸ್ತಾಪಿಸಿ',
            'dashboard.propose_desc': 'ಹೊಸ ಪಾಲುದಾರ ಸಂಸ್ಥೆಯನ್ನು ಶಿಫಾರಸು ಮಾಡಿ.',
            'solutions.title': 'ಪರಿಹಾರಗಳು',
            'solutions.submit_new': 'ಹೊಸ ಪರಿಹಾರವನ್ನು ಸಲ್ಲಿಸಿ',
            'solutions.details': 'ಪರಿಹಾರ ವಿವರಗಳು',
            'partners.title': 'ಪಾಲುದಾರರು',
            'partners.propose_new': 'ಹೊಸ ಪಾಲುದಾರನನ್ನು ಪ್ರಸ್ತಾಪಿಸಿ',
            'partners.details': 'ಪಾಲುದಾರ ವಿವರಗಳು',
            'tickets.title': 'ಟಿಕೆಟ್‌ಗಳು',
            'tickets.submit_new': 'ಹೊಸ ಟಿಕೆಟ್ ಸಲ್ಲಿಸಿ',
            'tickets.details': 'ಟಿಕೆಟ್ ವಿವರಗಳು',
            'tickets.approve_request': 'ವಿನಂತಿಯನ್ನು ಅನುಮೋದಿಸಿ',
            'reports.title': 'ಪರಿಹಾರ ವರದಿ',
            'reports.back_to_solutions': 'ಪರಿಹಾರಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
            'reports.status_filter': 'ಪರಿಹಾರ ಸ್ಥಿತಿ',
            'reports.by_domain': 'ಡೊಮೇನ್ ಮೂಲಕ ಪರಿಹಾರಗಳು',
            'reports.by_provider': 'ಪೂರೈಕೆದಾರರ ಮೂಲಕ ಪರಿಹಾರಗಳು',
            'reports.found': 'ಪರಿಹಾರಗಳು ಕಂಡುಬಂದಿವೆ',
            'reports.no_match': 'ಆಯ್ದ ಮಾನದಂಡಗಳಿಗೆ ಯಾವುದೇ ಪರಿಹಾರಗಳು ಹೊಂದಿಕೆಯಾಗುವುದಿಲ್ಲ.',
            'list.view_action': 'ವೀಕ್ಷಿಸಿ',
            'list.column_name': 'ಹೆಸರು',
            'list.column_domain': 'ಡೊಮೇನ್',
            'list.column_status': 'ಸ್ಥಿತಿ',
            'list.column_org': 'ಸಂಸ್ಥೆ',
            'list.column_type': 'ಪ್ರಕಾರ',
            'list.column_proposed_by': 'ಪ್ರಸ್ತಾಪಿಸಿದವರು',
            'list.column_title': 'ಶೀರ್ಷಿಕೆ',
            'list.toggle_list': 'ಪಟ್ಟಿ',
            'list.toggle_ai': 'AI ಸಹಾಯಕ',
            'list.search_placeholder': 'ಹುದುಕಿ...',
            'list.go': 'ಹೋಗಿ',
            'list.create_new': 'ಹೊಸದನ್ನು ರಚಿಸಿ',
            'list.page_label': 'ಪುಟ',
            // Enums
            'domain.Water': 'ನೀರು',
            'domain.Health': 'ಆರೋಗ್ಯ',
            'domain.Energy': 'ಶಕ್ತಿ',
            'domain.Education': 'ಶಿಕ್ಷಣ',
            'domain.Livelihood': 'ಜೀವನೋಪಾಯ',
            'domain.Sustainability': 'ಸುಸ್ಥಿರತೆ',
            'status.PROPOSED': 'ಪ್ರಸ್ತಾಪಿಸಲಾಗಿದೆ',
            'status.DRAFT': 'ಕರಡು',
            'status.PENDING': 'ಬಾಕಿ ಉಳಿದಿದೆ',
            'status.APPROVED': 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
            'status.MATURE': 'ಪರಿಪಕ್ವ',
            'status.PILOT': 'ಪೈಲಟ್',
            'status.REJECTED': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
            'status.NEW': 'ಹೊಸ',
            'status.IN_PROGRESS': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
            'status.RESOLVED': 'ಪರಿಹರಿಸಲಾಗಿದೆ',
            'status.CLOSED': 'ಮುಚ್ಚಲಾಗಿದೆ',
            // Partner Entity Types
            'entity_type.NGO': 'ಎನ್‌ಜಿಒ',
            'entity_type.Social Impact Entity': 'ಸಾಮಾಜಿಕ ಪ್ರಭಾವ ಘಟಕ',
            'entity_type.Academic': 'ಶೈಕ್ಷಣಿಕ',
            'entity_type.Corporate': 'ಕಾರ್ಪೊರೇಟ್',
            // Form Titles & Labels
            'System Info': 'ಸಿಸ್ಟಮ್ ಮಾಹಿತಿ',
            'Solution Overview': 'ಪರಿಹಾರ ಅವಲೋಕನ',
            'Impact & Benefits': 'ಪರಿಣಾಮ ಮತ್ತು ಲಾಭಗಳು',
            'Implementation Details': 'ಅನುಷ್ಠಾನ ವಿವರಗಳು',
            'Resources': 'ಸಂಪನ್ಮೂಲಗಳು',
            'Attachments': 'ಲಗತ್ತುಗಳು',
            'ID': 'ಐಡಿ',
            'Created At': 'ರಚಿಸಲಾಗಿದೆ',
            'Updated At': 'ನವೀಕರಿಸಲಾಗಿದೆ',
            'Solution Name': 'ಪರಿಹಾರದ ಹೆಸರು',
            'Summary (One Line)': 'ಸಾರಾಂಶ (ಒಂದು ಸಾಲು)',
            'Detailed Description': 'ವಿವರವಾದ ವಿವರಣೆ',
            'Domain': 'ಡೊಮೇನ್',
            'Vertical Domain': 'ಲಂಬ ಡೊಮೇನ್',
            'Unique Value Proposition (Benefit)': 'ಅನನ್ಯ ಮೌಲ್ಯ ಪ್ರತಿಪಾದನೆ (ಲಾಭ)',
            'Cost and Effort': 'ವೆಚ್ಚ ಮತ್ತು ಶ್ರಮ',
            'Return on Investment (ROI)': 'ಹೂಡಿಕೆಯ ಮೇಲಿನ ಆದಾಯ (ROI)',
            'Launch Year': 'ಪ್ರಾರಂಭ ವರ್ಷ',
            'Target Beneficiaries': 'ಗುರಿ ಫಲಾನುಭವಿಗಳು',
            'References (Links)': 'ಉಲ್ಲೇಖಗಳು (ಲಿಂಕ್‌ಗಳು)',
            'Status': 'ಸ್ಥಿತಿ',
            'Provided By Partner ID': 'ಪಾಲುದಾರ ಐಡಿ ಮೂಲಕ ಒದಗಿಸಲಾಗಿದೆ',
            'Provided By Partner Name': 'ಪಾಲುದಾರ ಹೆಸರಿನ ಮೂಲಕ ಒದಗಿಸಲಾಗಿದೆ',
            'Proposed By User ID': 'ಪ್ರಸ್ತಾಪಿತ ಬಳಕೆದಾರ ಐಡಿ',
            'Proposed By User Name': 'ಪ್ರಸ್ತಾಪಿತ ಬಳಕೆದಾರ ಹೆಸರು',
            // Partner Form Labels
            'Organization Details': 'ಸಂಸ್ಥೆಯ ವಿವರಗಳು',
            'Contact Details': 'ಸಂಪರ್ಕ ವಿವರಗಳು',
            'Location': 'ಸ್ಥಳ',
            'Organization Name': 'ಸಂಸ್ಥೆಯ ಹೆಸರು',
            'Entity Type': 'ಸಂಸ್ಥೆಯ ಪ್ರಕಾರ',
            'Website URL': 'ವೆಬ್‌ಸೈಟ್ URL',
            'Contact Information': 'ಸಂಪರ್ಕ ಮಾಹಿತಿ',
            'Address': 'ವಿಳಾಸ',
            'Email': 'ಇಮೇಲ್',
            'Phone': 'ದೂರವಾಣಿ',
            'City': 'ನಗರ',
            'Country': 'ದೇಶ',
            'Proposer ID': 'ಪ್ರಸ್ತಾಪಕ ಐಡಿ',
            'Proposed By': 'ಮೂಲಕ ಪ್ರಸ್ತಾಪಿಸಲಾಗಿದೆ'
        },
        'ml': {
            'nav.dashboard': 'ഡാഷ്ബോർഡ്',
            'nav.solutions': 'പരിഹാരങ്ങൾ',
            'nav.partners': 'പങ്കാളികൾ',
            'nav.tickets': 'ടിക്കറ്റുകൾ',
            'nav.users': 'ഉപയോക്താക്കൾ',
            'nav.reports': 'റിപ്പോർട്ടുകൾ',
            'nav.login': 'ലോഗിൻ / രജിസ്റ്റർ',
            'nav.logout': 'ലോഗ് ഔട്ട്',
            'common.back': 'തിരികെ',
            'common.save': 'സംരക്ഷിക്കുക',
            'common.cancel': 'റദ്ദാക്കുക',
            'common.full_catalog': 'പൂർണ്ണ കാറ്റലോഗ്',
            'common.back_to_list': 'ലിസ്റ്റിലേക്ക് മടങ്ങുക',
            'common.ai_import': 'AI സഹായത്തോടെയുള്ള ഇറക്കുമതി',
            'dashboard.total_solutions': 'ആകെ പരിഹാരങ്ങൾ',
            'dashboard.active_partners': 'സജീവ പങ്കാളികൾ',
            'dashboard.my_tickets': 'എന്റെ ടിക്കറ്റുകൾ',
            'common.view_all': 'എല്ലാം കാണുക',
            'dashboard.quick_actions': 'വേഗത്തിലുള്ള നടപടികൾ',
            'dashboard.submit_solution': 'ഒരു പരിഹാരം സമർപ്പിക്കുക',
            'dashboard.submit_desc': 'നിങ്ങളുടെ നൂതന ആശയം പ്ലാറ്റ്‌ഫോമുമായി പങ്കിടുക.',
            'dashboard.propose_partner': 'ഒരു പങ്കാളിയെ നിർദ്ദേശിക്കുക',
            'dashboard.propose_desc': 'ഒരു പുതിയ പങ്കാളി സംഘടനയെ ശുപാർശ ചെയ്യുക.',
            'solutions.title': 'പരിഹാരങ്ങൾ',
            'solutions.submit_new': 'പുതിയ പരിഹാരം സമർപ്പിക്കുക',
            'solutions.details': 'പരിഹാര വിശദാംശങ്ങൾ',
            'partners.title': 'പങ്കാളികൾ',
            'partners.propose_new': 'പുതിയ പങ്കാളിയെ നിർദ്ദേശിക്കുക',
            'partners.details': 'പങ്കാളി വിശദാംശങ്ങൾ',
            'tickets.title': 'ടിക്കറ്റുകൾ',
            'tickets.submit_new': 'പുതിയ ടിക്കറ്റ് സമർപ്പിക്കുക',
            'tickets.details': 'ടിക്കറ്റ് വിശദാംശങ്ങൾ',
            'tickets.approve_request': 'അഭ്യർത്ഥന അംഗീകരിക്കുക',
            'reports.title': 'പരിഹാര റിപ്പോർട്ട്',
            'reports.back_to_solutions': 'പരിഹാരങ്ങളിലേക്ക് മടങ്ങുക',
            'reports.status_filter': 'പരിഹാര നില',
            'reports.by_domain': 'ഡൊമെയ്ൻ അടിസ്ഥാനമാക്കിയുള്ള പരിഹാരങ്ങൾ',
            'reports.by_provider': 'ദാതാവ് അടിസ്ഥാനമാക്കിയുള്ള പരിഹാരങ്ങൾ',
            'reports.found': 'പരിഹാരങ്ങൾ കണ്ടെത്തി',
            'reports.no_match': 'തിരഞ്ഞെടുത്ത മാനദണ്ഡങ്ങളുമായി പൊരുത്തപ്പെടുന്ന പരിഹാരങ്ങളൊന്നുമില്ല.',
            'list.view_action': 'കാണുക',
            'list.column_name': 'പേര്',
            'list.column_domain': 'ഡൊമെയ്ൻ',
            'list.column_status': 'നില',
            'list.column_org': 'സംഘടന',
            'list.column_type': 'തരം',
            'list.column_proposed_by': 'നിർദ്ദേശിച്ചത്',
            'list.column_title': 'തലക്കെട്ട്',
            'list.toggle_list': 'ലിസ്റ്റ്',
            'list.toggle_ai': 'AI അസിസ്റ്റന്റ്',
            'list.search_placeholder': 'തിരയുക...',
            'list.go': 'പോകൂ',
            'list.create_new': 'പുതിയത് സൃഷ്ടിക്കുക',
            'list.page_label': 'പേജ്',
            // Enums
            'domain.Water': 'വെള്ളം',
            'domain.Health': 'ആരോഗ്യം',
            'domain.Energy': 'ഊർജ്ജം',
            'domain.Education': 'വിദ്യാഭ്യാസം',
            'domain.Livelihood': 'ഉപജീവനമാർഗ്ഗം',
            'domain.Sustainability': 'സുസ്ഥിരത',
            'status.PROPOSED': 'നിർദ്ദേശിച്ചത്',
            'status.DRAFT': 'കരട്',
            'status.PENDING': 'തീർപ്പുകൽപ്പിക്കാത്തത്',
            'status.APPROVED': 'അംഗീകരിച്ചത്',
            'status.MATURE': 'പൂർണ്ണമായ',
            'status.PILOT': 'പൈലറ്റ്',
            'status.REJECTED': 'നിരസിച്ചു',
            'status.NEW': 'പുതിയത്',
            'status.IN_PROGRESS': 'പുരോഗതിയിലാണ്',
            'status.RESOLVED': 'പരിഹരിച്ചു',
            'status.CLOSED': 'അടച്ചു',
            // Partner Entity Types
            'entity_type.NGO': 'എൻജിഒ',
            'entity_type.Social Impact Entity': 'സോഷ്യൽ ഇംപാക്ട് എന്റിറ്റി',
            'entity_type.Academic': 'അക്കാദമിക്',
            'entity_type.Corporate': 'കോർപ്പറേറ്റ്',
            // Form Titles & Labels
            'System Info': 'സിസ്റ്റം വിവരങ്ങൾ',
            'Solution Overview': 'പരിഹാര അവലോകനം',
            'Impact & Benefits': 'സ്വാധീനവും നേട്ടങ്ങളും',
            'Implementation Details': 'നടപ്പിലാക്കൽ വിശദാംശങ്ങൾ',
            'Resources': 'വിഭവങ്ങൾ',
            'Attachments': 'അറ്റാച്ചുമെന്റുകൾ',
            'ID': 'ഐഡി',
            'Created At': 'സൃഷ്ടിച്ചത്',
            'Updated At': 'അപ്ഡേറ്റ് ചെയ്തത്',
            'Solution Name': 'പരിഹാരത്തിന്റെ പേര്',
            'Summary (One Line)': 'സംഗ്രഹം (ഒരു വരി)',
            'Detailed Description': 'വിശദമായ വിവരണം',
            'Domain': 'ഡൊമെയ്ൻ',
            'Vertical Domain': 'ലംബ ഡൊമെയ്ൻ',
            'Unique Value Proposition (Benefit)': 'അതുല്യ മൂല്യ നിർദ്ദേശം (നേട്ടം)',
            'Cost and Effort': 'ചെലവും പരിശ്രമവും',
            'Return on Investment (ROI)': 'നിക്ഷേപത്തിൻ്റെ തിരിച്ചുവരവ് (ROI)',
            'Launch Year': 'ആരംഭ വർഷം',
            'Target Beneficiaries': 'ലക്ഷ്യ ഗുണഭോക്താക്കൾ',
            'References (Links)': 'റഫറൻസുകൾ (ലിങ്കുകൾ)',
            'Status': 'നില',
            'Provided By Partner ID': 'പങ്കാളി ഐഡി നൽകിയത്',
            'Provided By Partner Name': 'പങ്കാളിയുടെ പേര് നൽകിയത്',
            'Proposed By User ID': 'നിർദ്ദേശിച്ച ഉപയോക്തൃ ഐഡി',
            'Proposed By User Name': 'നിർദ്ദേശിച്ച ഉപയോക്തൃ നാമം',
            // Partner Form Labels
            'Organization Details': 'സംഘടനയുടെ വിശദാംശങ്ങൾ',
            'Contact Details': 'ബന്ധപ്പെടാനുള്ള വിശദാംശങ്ങൾ',
            'Location': 'സ്ഥലം',
            'Organization Name': 'സംഘടനയുടെ പേര്',
            'Entity Type': 'സ്ഥാപന തരം',
            'Website URL': 'വെബ്സൈറ്റ് URL',
            'Contact Information': 'ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ',
            'Address': 'വിലാസം',
            'Email': 'ഇമെയിൽ',
            'Phone': 'ഫോൺ',
            'City': 'നഗരം',
            'Country': 'രാജ്യം',
            'Proposer ID': 'നിർദ്ദേശക ഐഡി',
            'Proposed By': 'നിർദ്ദേശിച്ചത്'
        },
        'pa': {
            'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
            'nav.solutions': 'ਹੱਲ',
            'nav.partners': 'ਭਾਈਵਾਲ',
            'nav.tickets': 'ਟਿਕਟਾਂ',
            'nav.users': 'ਉਪਭੋਗਤਾ',
            'nav.reports': 'ਰਿਪੋਰਟਾਂ',
            'nav.login': 'ਲੌਗਇਨ / ਰਜਿਸਟਰ',
            'nav.logout': 'ਲੌਗ ਆਉਟ',
            'common.back': 'ਪਿੱਛੇ',
            'common.save': 'ਸੇਵ ਕਰੋ',
            'common.cancel': 'ਰੱਦ ਕਰੋ',
            'common.full_catalog': 'ਪੂਰਾ ਕੈਟਾਲਾਗ',
            'common.back_to_list': 'ਸੂਚੀ ਤੇ ਵਾਪਸ ਜਾਓ',
            'common.ai_import': 'AI ਸਹਾਇਤਾ ਪ੍ਰਾਪਤ ਆਯਾਤ',
            'dashboard.total_solutions': 'ਕੁੱਲ ਹੱਲ',
            'dashboard.active_partners': 'ਸਰਗਰਮ ਭਾਈਵਾਲ',
            'dashboard.my_tickets': 'ਮੇਰੀਆਂ ਟਿਕਟਾਂ',
            'common.view_all': 'ਸਭ ਦੇਖੋ',
            'dashboard.quick_actions': 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ',
            'dashboard.submit_solution': 'ਹੱਲ ਜਮ੍ਹਾਂ ਕਰੋ',
            'dashboard.submit_desc': 'ਪਲੇਟਫਾਰਮ ਨਾਲ ਆਪਣਾ ਨਵੀਨਤਾਕਾਰੀ ਹੱਲ ਸਾਂਝਾ ਕਰੋ।',
            'dashboard.propose_partner': 'ਭਾਈਵਾਲ ਦਾ ਪ੍ਰਸਤਾਵ',
            'dashboard.propose_desc': 'ਨਵੀਂ ਭਾਈਵਾਲ ਸੰਸਥਾ ਦੀ ਸਿਫਾਰਸ਼ ਕਰੋ।',
            'solutions.title': 'ਹੱਲ',
            'solutions.submit_new': 'ਨਵਾਂ ਹੱਲ ਜਮ੍ਹਾਂ ਕਰੋ',
            'solutions.details': 'ਹੱਲ ਵੇਰਵੇ',
            'partners.title': 'ਭਾਈਵਾਲ',
            'partners.propose_new': 'ਨਵਾਂ ਭਾਈਵਾਲ ਪ੍ਰਸਤਾਵਿਤ ਕਰੋ',
            'partners.details': 'ਭਾਈਵਾਲ ਵੇਰਵੇ',
            'tickets.title': 'ਟਿਕਟਾਂ',
            'tickets.submit_new': 'ਨਵੀਂ ਟਿਕਟ ਜਮ੍ਹਾਂ ਕਰੋ',
            'tickets.details': 'ਟਿਕਟ ਵੇਰਵੇ',
            'tickets.approve_request': 'ਬੇਨਤੀ ਮਨਜ਼ੂਰ ਕਰੋ',
            'reports.title': 'ਹੱਲ ਰਿਪੋਰਟ',
            'reports.back_to_solutions': 'ਹੱਲਾਂ ਤੇ ਵਾਪਸ ਜਾਓ',
            'reports.status_filter': 'ਹੱਲ ਸਥਿਤੀ',
            'reports.by_domain': 'ਡੋਮੇਨ ਦੁਆਰਾ ਹੱਲ',
            'reports.by_provider': 'ਪ੍ਰਦਾਤਾ ਦੁਆਰਾ ਹੱਲ',
            'reports.found': 'ਹੱਲ ਮਿਲੇ',
            'reports.no_match': 'ਚੁਣੇ ਗਏ ਮਾਪਦੰਡਾਂ ਨਾਲ ਕੋਈ ਹੱਲ ਮੇਲ ਨਹੀਂ ਖਾਂਦਾ।',
            'list.view_action': 'ਵੇਖੋ',
            'list.column_name': 'ਨਾਮ',
            'list.column_domain': 'ਡੋਮੇਨ',
            'list.column_status': 'ਸਥਿਤੀ',
            'list.column_org': 'ਸੰਸਥਾ',
            'list.column_type': 'ਕਿਸਮ',
            'list.column_proposed_by': 'ਪ੍ਰਸਤਾਵਿਤ',
            'list.column_title': 'ਸਿਰਲੇਖ',
            'list.toggle_list': 'ਸੂਚੀ',
            'list.toggle_ai': 'AI ਸਹਾਇਕ',
            'list.search_placeholder': 'ਖੋਜ...',
            'list.go': 'ਜਾਓ',
            'list.create_new': 'ਨਵਾਂ ਬਣਾਓ',
            'list.page_label': 'ਪੰਨਾ',
            // Enums
            'domain.Water': 'ਪਾਣੀ',
            'domain.Health': 'ਸਿਹਤ',
            'domain.Energy': 'ਊਰਜਾ',
            'domain.Education': 'ਸਿੱਖਿਆ',
            'domain.Livelihood': 'ਰੋਜ਼ੀ-ਰੋਟੀ',
            'domain.Sustainability': 'ਸਥਿਰਤਾ',
            'status.PROPOSED': 'ਪ੍ਰਸਤਾਵਿਤ',
            'status.DRAFT': 'ਡਰਾਫਟ',
            'status.PENDING': 'ਬਕਾਇਆ',
            'status.APPROVED': 'ਮਨਜ਼ੂਰ',
            'status.MATURE': 'ਪੂਰਾ',
            'status.PILOT': 'ਪਾਇਲਟ',
            'status.REJECTED': 'ਰੱਦ ਕੀਤਾ',
            'status.NEW': 'ਨਵਾਂ',
            'status.IN_PROGRESS': 'ਪ੍ਰਗਤੀ ਵਿੱਚ',
            'status.RESOLVED': 'ਹੱਲ ਕੀਤਾ',
            'status.CLOSED': 'ਬੰਦ',
            // Partner Entity Types
            'entity_type.NGO': 'ਐਨ.ਜੀ.ਓ',
            'entity_type.Social Impact Entity': 'ਸਮਾਜਿਕ ਪ੍ਰਭਾਵ ਸੰਸਥਾ',
            'entity_type.Academic': 'ਵਿੱਦਿਅਕ',
            'entity_type.Corporate': 'ਕਾਰਪੋਰੇਟ',
            // Form Titles & Labels
            'System Info': 'ਸਿਸਟਮ ਜਾਣਕਾਰੀ',
            'Solution Overview': 'ਹੱਲ ਬਾਰੇ ਜਾਣਕਾਰੀ',
            'Impact & Benefits': 'ਪ੍ਰਭਾਵ ਅਤੇ ਲਾਭ',
            'Implementation Details': 'ਲਾਗੂ ਕਰਨ ਦੇ ਵੇਰਵੇ',
            'Resources': 'ਸਰੋਤ',
            'Attachments': 'ਨੱਥੀ ਫਾਈਲਾਂ',
            'ID': 'ਆਈਡੀ',
            'Created At': 'ਬਣਾਇਆ ਗਿਆ',
            'Updated At': 'ਅੱਪਡੇਟ ਕੀਤਾ',
            'Solution Name': 'ਹੱਲ ਦਾ ਨਾਮ',
            'Summary (One Line)': 'ਸੰਖੇਪ (ਇੱਕ ਲਾਈਨ)',
            'Detailed Description': 'ਵਿਸਤ੍ਰਿਤ ਵੇਰਵਾ',
            'Domain': 'ਡੋਮੇਨ',
            'Vertical Domain': 'ਵਰਟੀਕਲ ਡੋਮੇਨ',
            'Unique Value Proposition (Benefit)': 'ਵਿਲੱਖਣ ਮੁੱਲ ਪ੍ਰਸਤਾਵ (ਲਾਭ)',
            'Cost and Effort': 'ਲਾਗਤ ਅਤੇ ਕੋਸ਼ਿਸ਼',
            'Return on Investment (ROI)': 'ਨਿਵੇਸ਼ ਤੇ ਵਾਪਸੀ (ROI)',
            'Launch Year': 'ਲਾਂਚ ਸਾਲ',
            'Target Beneficiaries': 'ਟੀਚਾ ਲਾਭਪਾਤਰੀ',
            'References (Links)': 'ਹਵਾਲੇ (ਲਿੰਕ)',
            'Status': 'ਸਥਿਤੀ',
            'Provided By Partner ID': 'ਭਾਈਵਾਲ ਆਈਡੀ ਦੁਆਰਾ ਪ੍ਰਦਾਨ ਕੀਤਾ ਗਿਆ',
            'Provided By Partner Name': 'ਭਾਈਵਾਲ ਨਾਮ ਦੁਆਰਾ ਪ੍ਰਦਾਨ ਕੀਤਾ ਗਿਆ',
            'Proposed By User ID': 'ਪ੍ਰਸਤਾਵਿਤ ਉਪਭੋਗਤਾ ਆਈਡੀ',
            'Proposed By User Name': 'ਪ੍ਰਸਤਾਵਿਤ ਉਪਭੋਗਤਾ ਨਾਮ',
            // Partner Form Labels
            'Organization Details': 'ਸੰਸਥਾ ਦੇ ਵੇਰਵੇ',
            'Contact Details': 'ਸੰਪਰਕ ਵੇਰਵੇ',
            'Location': 'ਸਥਾਨ',
            'Organization Name': 'ਸੰਸਥਾ ਦਾ ਨਾਮ',
            'Entity Type': 'ਸੰਸਥਾ ਦੀ ਕਿਸਮ',
            'Website URL': 'ਵੈਬਸਾਈਟ URL',
            'Contact Information': 'ਸੰਪਰਕ ਜਾਣਕਾਰੀ',
            'Address': 'ਪਤਾ',
            'Email': 'ਈਮੇਲ',
            'Phone': 'ਫੋਨ',
            'City': 'ਸ਼ਹਿਰ',
            'Country': 'ਦੇਸ਼',
            'Proposer ID': 'ਪ੍ਰਸਤਾਵਕ ਆਈਡੀ',
            'Proposed By': 'ਦੁਆਰਾ ਪ੍ਰਸਤਾਵਿਤ'
        }
    } as any;

    const t = (text: string): string => {
        const langDict = DICTIONARY[language];
        const enDict = DICTIONARY['en'];
        // Fallback: Language Specific -> English -> Original Key
        return langDict?.[text] || enDict?.[text] || text;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, direction, t }}>
            <div dir={direction} style={{ minHeight: '100vh', width: '100%' }}>
                {children}
            </div>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export const SUPPORTED_LANGUAGES = LANGUAGES;
