import { createContext, useState, useContext, useEffect, type ReactNode } from 'react';
import { useAuth } from './AuthContext';

export type LanguageCode = 'en' | 'hi' | 'bn' | 'te' | 'mr' | 'ta' | 'ur' | 'gu' | 'kn' | 'ml' | 'pa';

export interface LanguageContextType {
    language: LanguageCode;
    setLanguage: (lang: LanguageCode) => void;
    direction: 'ltr' | 'rtl';
    t: (text: string) => string; // Placeholder for UI strings translation
}

const LANGUAGES: Record<LanguageCode, { name: string; dir: 'ltr' | 'rtl' }> = {
    'en': { name: 'English', dir: 'ltr' },
    'hi': { name: 'Hindi', dir: 'ltr' },
    'bn': { name: 'Bengali', dir: 'ltr' },
    'te': { name: 'Telugu', dir: 'ltr' },
    'mr': { name: 'Marathi', dir: 'ltr' },
    'ta': { name: 'Tamil', dir: 'ltr' },
    'ur': { name: 'Urdu', dir: 'rtl' },
    'gu': { name: 'Gujarati', dir: 'ltr' },
    'kn': { name: 'Kannada', dir: 'ltr' },
    'ml': { name: 'Malayalam', dir: 'ltr' },
    'pa': { name: 'Punjabi', dir: 'ltr' }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const { user } = useAuth();
    const [language, setLanguageState] = useState<LanguageCode>('en');

    // Initialize from user profile if available, else local storage, else 'en'
    useEffect(() => {
        if (user?.language) {
            setLanguageState(user.language as LanguageCode);
        } else {
            const saved = localStorage.getItem('app_language') as LanguageCode;
            if (saved && LANGUAGES[saved]) {
                setLanguageState(saved);
            }
        }
    }, [user?.language]);

    const setLanguage = (lang: LanguageCode) => {
        setLanguageState(lang);
        localStorage.setItem('app_language', lang);

        // Update user profile if logged in
        // We'll trust the component calling this to trigger the API update or we do it here?
        // Let's do it here for convenience if user is logged in.
        // But we need an API client. For now, we'll just update state and localStorage.
        // The Selector component can handle the API call or we can add it here if we had api client imported.
    };

    const direction = LANGUAGES[language].dir;

    // UI Dictionary
    const DICTIONARY: Record<LanguageCode, Record<string, string>> = {
        'en': {
            'nav.dashboard': 'Dashboard',
            'nav.solutions': 'Solutions',
            'nav.partners': 'Partners',
            'nav.tickets': 'Tickets',
            'nav.users': 'Users',
            'nav.reports': 'Reports',
            'nav.login': 'Login / Register',
            'nav.logout': 'Logout',
            'common.back': 'Back',
            'common.save': 'Save',
            'common.cancel': 'Cancel',
            'common.full_catalog': 'Full Catalog',
            'common.back_to_list': 'Back to List',
            'common.ai_import': 'AI Assisted Import',
            'dashboard.total_solutions': 'Total Solutions',
            'dashboard.active_partners': 'Active Partners',
            'dashboard.my_tickets': 'My Tickets',
            'common.view_all': 'View All',
            'dashboard.quick_actions': 'Quick Actions',
            'dashboard.submit_solution': 'Submit a Solution',
            'dashboard.submit_desc': 'Share your innovative solution with the platform.',
            'dashboard.propose_partner': 'Propose a Partner',
            'dashboard.propose_desc': 'Recommend a new partner organization.',
            'solutions.title': 'Solutions',
            'solutions.submit_new': 'Submit New Solution',
            'solutions.details': 'Solution Details',
            'partners.title': 'Partners',
            'partners.propose_new': 'Propose New Partner',
            'partners.details': 'Partner Details',
            'tickets.title': 'Tickets',
            'tickets.submit_new': 'Submit New Ticket',
            'tickets.details': 'Ticket Details',
            'tickets.approve_request': 'Approve Request',
            'reports.title': 'Solutions Report',
            'reports.back_to_solutions': 'Back to Solutions',
            'reports.status_filter': 'Solution Status',
            'reports.by_domain': 'Solutions by Domain',
            'reports.by_provider': 'Solutions by Provider',
            'reports.found': 'Solutions Found',
            'reports.no_match': 'No solutions match the selected criteria.',
            'list.view_action': 'View',
            'list.column_name': 'Name',
            'list.column_domain': 'Domain',
            'list.column_status': 'Status',
            'list.column_org': 'Organization',
            'list.column_type': 'Type',
            'list.column_proposed_by': 'Proposed By',
            'list.column_title': 'Title',
            'list.toggle_list': 'List',
            'list.toggle_ai': 'AI Assistant',
            'list.search_placeholder': 'Search...',
            'list.go': 'Go',
            'list.create_new': 'Create New',
            'list.page_label': 'Page',
            // Enums
            'domain.Water': 'Water',
            'domain.Health': 'Health',
            'domain.Energy': 'Energy',
            'domain.Education': 'Education',
            'domain.Livelihood': 'Livelihood',
            'domain.Sustainability': 'Sustainability',
            'status.PROPOSED': 'PROPOSED',
            'status.DRAFT': 'DRAFT',
            'status.PENDING': 'PENDING',
            'status.APPROVED': 'APPROVED',
            'status.MATURE': 'MATURE',
            'status.PILOT': 'PILOT',
            'status.REJECTED': 'REJECTED',
            'status.NEW': 'NEW',
            'status.IN_PROGRESS': 'IN_PROGRESS',
            'status.RESOLVED': 'RESOLVED',
            'status.CLOSED': 'CLOSED',
            // Partner Entity Types
            'entity_type.NGO': 'NGO',
            'entity_type.Social Impact Entity': 'Social Impact Entity',
            'entity_type.Academic': 'Academic',
            'entity_type.Corporate': 'Corporate',
            // Form Titles & Labels (Explicit mapping, though redundant if key==value, useful for strict t())
            'System Info': 'System Info',
            'Solution Overview': 'Solution Overview',
            'Impact & Benefits': 'Impact & Benefits',
            'Implementation Details': 'Implementation Details',
            'Resources': 'Resources',
            'Attachments': 'Attachments',
            'ID': 'ID',
            'Created At': 'Created At',
            'Updated At': 'Updated At',
            'Solution Name': 'Solution Name',
            'Summary (One Line)': 'Summary (One Line)',
            'Detailed Description': 'Detailed Description',
            'Domain': 'Domain',
            'Vertical Domain': 'Vertical Domain',
            'Unique Value Proposition (Benefit)': 'Unique Value Proposition (Benefit)',
            'Cost and Effort': 'Cost and Effort',
            'Return on Investment (ROI)': 'Return on Investment (ROI)',
            'Launch Year': 'Launch Year',
            'Target Beneficiaries': 'Target Beneficiaries',
            'References (Links)': 'References (Links)',
            'Status': 'Status',
            'Provided By Partner ID': 'Provided By Partner ID',
            'Provided By Partner Name': 'Provided By Partner Name',
            'Proposed By User ID': 'Proposed By User ID',
            'Proposed By User Name': 'Proposed By User Name',
            // Partner Form Labels
            'Organization Details': 'Organization Details',
            'Contact Details': 'Contact Details',
            'Location': 'Location',
            'Organization Name': 'Organization Name',
            'Entity Type': 'Entity Type',
            'Website URL': 'Website URL',
            'Contact Information': 'Contact Information',
            'Address': 'Address',
            'Email': 'Email',
            'Phone': 'Phone',
            'City': 'City',
            'Country': 'Country',
            'Proposer ID': 'Proposer ID',
            'Proposed By': 'Proposed By'
        },
        'hi': {
            'nav.dashboard': 'डैशबोर्ड',
            'nav.solutions': 'समाधान',
            'nav.partners': 'साझेदार',
            'nav.tickets': 'टिकट',
            'nav.users': 'उपयोगकर्ता',
            'nav.reports': 'रिपोर्ट',
            'nav.login': 'लॉग इन / रजिस्टर',
            'nav.logout': 'लॉग आउट',
            'common.back': 'वापस',
            'common.save': 'सहेजें',
            'common.cancel': 'रद्द करें',
            'common.full_catalog': 'पूर्ण सूची',
            'common.back_to_list': 'सूची पर वापस जाएं',
            'common.ai_import': 'एआई सहायता प्राप्त आयात',
            'dashboard.total_solutions': 'कुल समाधान',
            'dashboard.active_partners': 'सक्रिय साझेदार',
            'dashboard.my_tickets': 'मेरे टिकट',
            'common.view_all': 'सभी देखें',
            'dashboard.quick_actions': 'त्वरित कार्रवाई',
            'dashboard.submit_solution': 'एक समाधान जमा करें',
            'dashboard.submit_desc': 'मंच के साथ अपना विचार साझा करें।',
            'dashboard.propose_partner': 'एक साथी प्रस्तावित करें',
            'dashboard.propose_desc': 'एक नए भागीदार संगठन की सिफारिश करें।',
            'solutions.title': 'समाधान',
            'solutions.submit_new': 'नया समाधान जमा करें',
            'solutions.details': 'समाधान विवरण',
            'partners.title': 'साझेदार',
            'partners.propose_new': 'नया साथी प्रस्तावित करें',
            'partners.details': 'साझेदार विवरण',
            'tickets.title': 'टिकट',
            'tickets.submit_new': 'नया टिकट जमा करें',
            'tickets.details': 'टिकट विवरण',
            'tickets.approve_request': 'अनुरोध स्वीकार करें',
            'reports.title': 'समाधान रिपोर्ट',
            'reports.back_to_solutions': 'समाधान पर वापस',
            'reports.status_filter': 'समाधान स्थिति',
            'reports.by_domain': 'डोमेन द्वारा समाधान',
            'reports.by_provider': 'प्रदाता द्वारा समाधान',
            'reports.found': 'समाधान मिले',
            'reports.no_match': 'चयनित मानदंड से कोई समाधान मेल नहीं खाता।',
            'list.view_action': 'देखें',
            'list.column_name': 'नाम',
            'list.column_domain': 'डोमेन',
            'list.column_status': 'स्थिति',
            'list.column_org': 'संगठन',
            'list.column_type': 'प्रकार',
            'list.column_proposed_by': 'प्रस्तावित द्वारा',
            'list.column_title': 'शीर्षक',
            'list.toggle_list': 'सूची',
            'list.toggle_ai': 'एआई सहायक',
            'list.search_placeholder': 'खोजें...',
            'list.go': 'जाएं',
            'list.create_new': 'नया बनाएँ',
            'list.page_label': 'पृष्ठ',
            // Enums
            'domain.Water': 'जल',
            'domain.Health': 'स्वास्थ्य',
            'domain.Energy': 'ऊर्जा',
            'domain.Education': 'शिक्षा',
            'domain.Livelihood': 'आजीविका',
            'domain.Sustainability': 'स्थिरता',
            'status.PROPOSED': 'प्रस्तावित',
            'status.DRAFT': 'मसौदा',
            'status.PENDING': 'लंबित',
            'status.APPROVED': 'स्वीकृत',
            'status.MATURE': 'परिपक्व',
            'status.PILOT': 'पायलट',
            'status.REJECTED': 'अस्वीकृत',
            'status.NEW': 'नया',
            'status.IN_PROGRESS': 'प्रगति पर',
            'status.RESOLVED': 'सुलझाया हुआ',
            'status.CLOSED': 'बंद',
            // Partner Entity Types
            'entity_type.NGO': 'एनजीओ (NGO)',
            'entity_type.Social Impact Entity': 'सामाजिक प्रभाव इकाई',
            'entity_type.Academic': 'अकादमिक',
            'entity_type.Corporate': 'कॉर्पोरेट',
            // Form Titles & Labels
            'System Info': 'सिस्टम जानकारी',
            'Solution Overview': 'समाधान अवलोकन',
            'Impact & Benefits': 'प्रभाव और लाभ',
            'Implementation Details': 'कार्यान्वयन विवरण',
            'Resources': 'संसाधन',
            'Attachments': 'संलग्नक',
            'ID': 'आईडी',
            'Created At': 'बनाया गया',
            'Updated At': 'अद्यतित',
            'Solution Name': 'समाधान का नाम',
            'Summary (One Line)': 'सारांश (एक पंक्ति)',
            'Detailed Description': 'विस्तृत विवरण',
            'Domain': 'डोमेन',
            'Vertical Domain': 'लंबवत डोमेन (Vertical Domain)',
            'Unique Value Proposition (Benefit)': 'अद्वितीय मूल्य प्रस्ताव (लाभ)',
            'Cost and Effort': 'लागत और प्रयास',
            'Return on Investment (ROI)': 'निवेश पर वापसी (ROI)',
            'Launch Year': 'लॉन्च वर्ष',
            'Target Beneficiaries': 'लक्षित लाभार्थी',
            'References (Links)': 'संदर्भ (लिंक)',
            'Status': 'स्थिति',
            'Provided By Partner ID': 'साझेदार आईडी द्वारा प्रदान किया गया',
            'Provided By Partner Name': 'साझेदार नाम द्वारा प्रदान किया गया',
            'Proposed By User ID': 'प्रस्तावित उपयोगकर्ता आईडी',
            'Proposed By User Name': 'प्रस्तावित उपयोगकर्ता नाम',
            // Partner Form Labels
            'Organization Details': 'संगठन विवरण',
            'Contact Details': 'संपर्क विवरण',
            'Location': 'स्थान',
            'Organization Name': 'संगठन का नाम',
            'Entity Type': 'इकाई का प्रकार',
            'Website URL': 'वेबसाइट यूआरएल',
            'Email': 'ईमेल',
            'Phone': 'फ़ोन',
            'City': 'शहर',
            'Country': 'देश',
            'Proposer ID': 'प्रस्तावक आईडी',
            'Proposed By': 'द्वारा प्रस्तावित'
        },
        // Fallback for others (keep basic nav)
        'bn': {
            'nav.dashboard': 'ড্যাশবোর্ড',
            'nav.solutions': 'সমাধান',
            'nav.partners': 'অংশীদার',
            'nav.tickets': 'টিকেট',
            'nav.users': 'ব্যবহারকারী',
            'nav.reports': 'রিপোর্ট',
            'nav.login': 'লগইন / রেজিস্টার',
            'nav.logout': 'লগআউট',
            'common.back': 'ফিরে যান',
            'common.save': 'সংরক্ষণ',
            'common.cancel': 'বাতিল',
            'common.view_all': 'সব দেখুন',
            'dashboard.submit_solution': 'একটি সমাধান জমা দিন',
            'dashboard.propose_partner': 'নতুন অংশীদার প্রস্তাব করুন',
            'solutions.title': 'সমাধান',
            'partners.title': 'অংশীদার',
            'list.search_placeholder': 'অনুসন্ধান...',
            // Enums
            'domain.Water': 'জল',
            'domain.Health': 'স্বাস্থ্য',
            'domain.Energy': 'শক্তি',
            'domain.Education': 'শিক্ষা',
            'domain.Livelihood': 'জীবিকা',
            'domain.Sustainability': 'স্থায়িত্ব',
            'status.PROPOSED': 'প্রস্তাবিত',
            'status.APPROVED': 'অনুমোদিত',
            'status.REJECTED': 'প্রত্যাখ্যাত',
            'status.MATURE': 'পরিপক্ক',
            'entity_type.NGO': 'এনজিও',
            'entity_type.Social Impact Entity': 'সামাজিক প্রভাব সংস্থা',
            'entity_type.Academic': 'একাডেমিক',
            'entity_type.Corporate': 'কর্পোরেট',
            // Labels
            'Organization Name': 'প্রতিষ্ঠানের নাম',
            'Entity Type': 'সংস্থার ধরন',
            'Location': 'অবস্থান',
            'Contact Details': 'যোগাযোগের বিবরণ',
            'Solution Name': 'সমাধানের নাম',
            'Summary (One Line)': 'সারসংক্ষেপ (এক লাইন)',
            'Description': 'বিবরণ',
            'Domain': 'ডোমেইন'
        },
        'te': {
            'nav.dashboard': 'డాష్‌బోర్డ్',
            'nav.solutions': 'పరిష్కారాలు',
            'nav.partners': 'భాగస్వామ్యులు',
            'nav.tickets': 'టిక్కెట్లు',
            'nav.users': 'వినియోగదారులు',
            'nav.reports': 'నివేదికలు',
            'nav.login': 'లాగిన్ / నమోదు',
            'nav.logout': 'లాగ్ అవుట్',
            'common.back': 'వెనుకకు',
            'common.save': 'సేవ్ చేయండి',
            'common.cancel': 'రద్దు చేయండి',
            'common.view_all': 'అన్నీ చూడండి',
            'dashboard.submit_solution': 'పరిష్కారాన్ని సమర్పించండి',
            'dashboard.propose_partner': 'భాగస్వామిని ప్రతిపాదించండి',
            'solutions.title': 'పరిష్కారాలు',
            'partners.title': 'భాగస్వామ్యులు',
            'list.search_placeholder': 'శోధించండి...',
            // Enums
            'domain.Water': 'నీరు',
            'domain.Health': 'ఆరోగ్యం',
            'domain.Energy': 'శక్తి',
            'domain.Education': 'విద్య',
            'domain.Livelihood': 'జీవనోపాధి',
            'domain.Sustainability': 'సుస్థిరత',
            'status.PROPOSED': 'ప్రతిపాదించబడింది',
            'status.APPROVED': 'ఆమోదించబడింది',
            'status.REJECTED': 'తిరస్కరించబడింది',
            'status.MATURE': 'పరిపక్వ',
            'entity_type.NGO': 'NGO',
            'entity_type.Social Impact Entity': 'సామాజిక ప్రభావ సంస్థ',
            'entity_type.Academic': 'అకాడమిక్',
            'entity_type.Corporate': 'కార్పొరేట్',
            // Labels
            'Organization Name': 'సంస్థ పేరు',
            'Entity Type': 'సంస్థ రకం',
            'Location': 'స్థానం',
            'Contact Details': 'సంప్రదింపు వివరాలు',
            'Solution Name': 'పరిష్కారం పేరు',
            'Summary (One Line)': 'సారాంశం (ఒక లైన్)',
            'Description': 'వి వివరణ',
            'Domain': 'డొమైన్'
        },
        'mr': {
            'nav.dashboard': 'डॅशबोर्ड',
            'nav.solutions': 'उपाय (Solutions)',
            'nav.partners': 'भागीदार',
            'nav.tickets': 'तिकिटे',
            'nav.users': 'वापरकर्ते',
            'nav.reports': 'अहवाल',
            'nav.login': 'लॉगिन / नोंदणी',
            'nav.logout': 'बाहेर पडणे',
            'common.back': 'मागे',
            'common.save': 'जतन करा',
            'common.cancel': 'रद्द करा',
            'common.view_all': 'सर्व पहा',
            'dashboard.submit_solution': 'उपाय सादर करा',
            'dashboard.propose_partner': 'भागीदार सुचवा',
            'solutions.title': 'उपाय',
            'partners.title': 'भागीदार',
            'list.search_placeholder': 'शोधा...',
            'domain.Water': 'पाणी',
            'domain.Health': 'आरोग्य',
            'domain.Energy': 'ऊर्जा',
            'domain.Education': 'शिक्षण',
            'domain.Livelihood': 'उपजीविका',
            'domain.Sustainability': 'शाश्वतता',
            'status.PROPOSED': 'प्रस्तावित',
            'status.APPROVED': 'मंजूर',
            'status.REJECTED': 'नाकारले',
            'status.MATURE': 'परिपक्व',
            'entity_type.NGO': 'एनजीओ',
            'entity_type.Social Impact Entity': 'सामाजिक प्रभाव संस्था',
            'entity_type.Academic': 'शैक्षणिक',
            'entity_type.Corporate': 'कॉर्पोरेट',
            'Organization Name': 'संस्थेचे नाव',
            'Entity Type': 'संस्थेचा प्रकार',
            'Location': 'स्थान',
            'Contact Details': 'संपर्क तपशील',
            'Solution Name': 'उपायाचे नाव',
            'Summary (One Line)': 'गोषवारा (एक ओळ)',
            'Description': 'वर्णन',
            'Domain': 'डोमेन'
        },
        'ta': {
            'nav.dashboard': 'டாஷ்போர்டு',
            'nav.solutions': 'தீர்வுகள்',
            'nav.partners': 'கூட்டாளர்கள்',
            'nav.tickets': 'டிக்கெட்டுகள்',
            'nav.users': 'பயனர்கள்',
            'nav.reports': 'அறிக்கைகள்',
            'nav.login': 'உள்நுழை / பதிவு',
            'nav.logout': 'வெளியேறு',
            'common.back': 'திரும்ப',
            'common.save': 'சேமி',
            'common.cancel': 'ரத்துசெய்',
            'common.view_all': 'அனைத்தையும் பார்',
            'dashboard.submit_solution': 'தீர்வைச் சமர்ப்பிக்கவும்',
            'dashboard.propose_partner': 'கூட்டாளரைப் பரிந்துரைக்கவும்',
            'solutions.title': 'தீர்வுகள்',
            'partners.title': 'கூட்டாளர்கள்',
            'list.search_placeholder': 'தேடு...',
            'domain.Water': 'நீர்',
            'domain.Health': 'சுகாதாரம்',
            'domain.Energy': 'ஆற்றல்',
            'domain.Education': 'கல்வி',
            'domain.Livelihood': 'வாழ்வாதாரம்',
            'domain.Sustainability': 'நிலைத்தன்மை',
            'status.PROPOSED': 'முன்மொழியப்பட்டது',
            'status.APPROVED': 'அங்கீகரிக்கப்பட்டது',
            'status.REJECTED': 'நிராகரிக்கப்பட்டது',
            'status.MATURE': 'முதிர்ந்த',
            'entity_type.NGO': 'தன்னார்வ தொண்டு நிறுவனம்',
            'entity_type.Social Impact Entity': 'சமூக தாக்க நிறுவனம்',
            'entity_type.Academic': 'கல்வி',
            'entity_type.Corporate': 'கார்ப்பரேட்',
            'Organization Name': 'நிறுவனத்தின் பெயர்',
            'Entity Type': 'நிறுவன வகை',
            'Location': 'இடம்',
            'Contact Details': 'தொடர்பு விவரங்கள்',
            'Solution Name': 'தீர்வு பெயர்',
            'Summary (One Line)': 'சுருக்கம் (ஒரு வரி)',
            'Description': 'விளக்கம்',
            'Domain': 'களம்'
        },
        'ur': {
            'nav.dashboard': 'ڈیش بورڈ',
            'nav.solutions': 'حل (Solutions)',
            'nav.partners': 'شراکت دار',
            'nav.tickets': 'ٹکٹس',
            'nav.users': 'صارفین',
            'nav.reports': 'رپورٹس',
            'nav.login': 'لاگ ان / رجسٹر',
            'nav.logout': 'لاگ آؤٹ',
            'common.back': 'پیچھے',
            'common.save': 'محفوظ کریں',
            'common.cancel': 'منسوخ کریں',
            'common.view_all': 'سب دیکھیں',
            'dashboard.submit_solution': 'نیا حل پیش کریں',
            'dashboard.propose_partner': 'نئے پارٹنر کی تجویز دیں',
            'solutions.title': 'حل',
            'partners.title': 'شراکت دار',
            'list.search_placeholder': 'تلاش کریں...',
            'domain.Water': 'پانی',
            'domain.Health': 'صحت',
            'domain.Energy': 'توانائی',
            'domain.Education': 'تعلیم',
            'domain.Livelihood': 'روزگار',
            'domain.Sustainability': 'پائیداری',
            'status.PROPOSED': 'تجویز کردہ',
            'status.APPROVED': 'منظور شدہ',
            'status.REJECTED': 'مسترد',
            'status.MATURE': 'پختہ',
            'entity_type.NGO': 'این جی او',
            'entity_type.Social Impact Entity': 'سوشل امپیکٹ اینٹیٹی',
            'entity_type.Academic': 'تعلیمی',
            'entity_type.Corporate': 'کارپوریٹ',
            'Organization Name': 'تنظیم کا نام',
            'Entity Type': 'ادارے کی قسم',
            'Location': 'مقام',
            'Contact Details': 'رابطہ کی تفصیلات',
            'Solution Name': 'حل کا نام',
            'Summary (One Line)': 'خلاصہ (ایک سطر)',
            'Description': 'تفصیل',
            'Domain': 'ڈومین'
        },
        'gu': {
            'nav.dashboard': 'ડેશબોર્ડ',
            'nav.solutions': 'ઉકેલો',
            'nav.partners': 'ભાગીદારો',
            'nav.tickets': 'ટિકિટ',
            'nav.users': 'વપરાશકર્તાઓ',
            'nav.reports': 'અહેવાલો',
            'nav.login': 'લૉગિન / રજીસ્ટર',
            'nav.logout': 'લૉગ આઉટ',
            'common.back': 'પાછા',
            'common.save': 'સાચવો',
            'common.cancel': 'રદ કરો',
            'common.view_all': 'બધું જુઓ',
            'dashboard.submit_solution': 'ઉકેલ સબમિટ કરો',
            'dashboard.propose_partner': 'ભાગીદાર સૂચવો',
            'solutions.title': 'ઉકેલો',
            'partners.title': 'ભાગીદારો',
            'list.search_placeholder': 'શોધો...',
            'domain.Water': 'પાણી',
            'domain.Health': 'આરોગ્ય',
            'domain.Energy': 'ઊર્જા',
            'domain.Education': 'શિક્ષણ',
            'domain.Livelihood': 'આજીવિકા',
            'domain.Sustainability': 'સ્થિરતા',
            'status.PROPOSED': 'પ્રસ્તાવિત',
            'status.APPROVED': 'માન્ય',
            'status.REJECTED': 'નકારાયેલ',
            'status.MATURE': 'વિકસિત',
            'entity_type.NGO': 'એનજીઓ',
            'entity_type.Social Impact Entity': 'સામાજિક અસર એકમ',
            'entity_type.Academic': 'શૈક્ષણિક',
            'entity_type.Corporate': 'કોર્પોરેટ',
            'Organization Name': 'સંસ્થાનું નામ',
            'Entity Type': 'એકમ પ્રકાર',
            'Location': 'સ્થાન',
            'Contact Details': 'સંપર્ક વિગતો',
            'Solution Name': 'ઉકેલ નામ',
            'Summary (One Line)': 'સારાંશ',
            'Description': 'વર્ણન',
            'Domain': 'ડોમેન'
        },
        'kn': {
            'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
            'nav.solutions': 'ಪರಿಹಾರಗಳು',
            'nav.partners': 'ಪಾಲುದಾರರು',
            'nav.tickets': 'ಟಿಕೆಟ್‌ಗಳು',
            'nav.users': 'ಬಳಕೆದಾರರು',
            'nav.reports': 'ವರದಿಗಳು',
            'nav.login': 'ಲಾಗಿನ್ / ನೋಂದಣಿ',
            'nav.logout': 'ಲಾಗ್ ಔಟ್',
            'common.back': 'ಹಿಂದೆ',
            'common.save': 'ಉಳಿಸಿ',
            'common.cancel': 'ರದ್ದುಮಾಡಿ',
            'common.view_all': 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
            'dashboard.submit_solution': 'ಪರಿಹಾರವನ್ನು ಸಲ್ಲಿಸಿ',
            'dashboard.propose_partner': 'ಪಾಲುದಾರನನ್ನು ಪ್ರಸ್ತಾಪಿಸಿ',
            'solutions.title': 'ಪರಿಹಾರಗಳು',
            'partners.title': 'ಪಾಲುದಾರರು',
            'list.search_placeholder': 'ಹುದುಕಿ...',
            'domain.Water': 'ನೀರು',
            'domain.Health': 'ಆರೋಗ್ಯ',
            'domain.Energy': 'ಶಕ್ತಿ',
            'domain.Education': 'ಶಿಕ್ಷಣ',
            'domain.Livelihood': 'ಜೀವನೋಪಾಯ',
            'domain.Sustainability': 'ಸುಸ್ಥಿರತೆ',
            'status.PROPOSED': 'ಪ್ರಸ್ತಾಪಿಸಲಾಗಿದೆ',
            'status.APPROVED': 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
            'status.REJECTED': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
            'status.MATURE': 'ಪರಿಪಕ್ವ',
            'entity_type.NGO': 'ಎನ್‌ಜಿಒ',
            'entity_type.Social Impact Entity': 'ಸಾಮಾಜಿಕ ಪ್ರಭಾವ ಘಟಕ',
            'entity_type.Academic': 'ಶೈಕ್ಷಣಿಕ',
            'entity_type.Corporate': 'ಕಾರ್ಪೊರೇಟ್',
            'Organization Name': 'ಸಂಸ್ಥೆಯ ಹೆಸರು',
            'Entity Type': 'ಸಂಸ್ಥೆಯ ಪ್ರಕಾರ',
            'Location': 'ಸ್ಥಳ',
            'Contact Details': 'ಸಂಪರ್ಕ ವಿವರಗಳು',
            'Solution Name': 'ಪರಿಹಾರದ ಹೆಸರು',
            'Summary (One Line)': 'ಸಾರಾಂಶ',
            'Description': 'ವಿವರಣೆ',
            'Domain': 'ಡೊಮೇನ್'
        },
        'ml': {
            'nav.dashboard': 'ഡാഷ്ബോർഡ്',
            'nav.solutions': 'പരിഹാരങ്ങൾ',
            'nav.partners': 'പങ്കാളികൾ',
            'nav.tickets': 'ടിക്കറ്റുകൾ',
            'nav.users': 'ഉപയോക്താക്കൾ',
            'nav.reports': 'റിപ്പോർട്ടുകൾ',
            'nav.login': 'ലോഗിൻ / രജിസ്റ്റർ',
            'nav.logout': 'ലോഗ് ഔട്ട്',
            'common.back': 'തിരികെ',
            'common.save': 'സംരക്ഷിക്കുക',
            'common.cancel': 'റദ്ദാക്കുക',
            'common.view_all': 'എല്ലാം കാണുക',
            'dashboard.submit_solution': 'പരിഹാരം സമർപ്പിക്കുക',
            'dashboard.propose_partner': 'പങ്കാളിയെ നിർദ്ദേശിക്കുക',
            'solutions.title': 'പരിഹാരങ്ങൾ',
            'partners.title': 'പങ്കാളികൾ',
            'list.search_placeholder': 'തിരയുക...',
            'domain.Water': 'വെള്ളം',
            'domain.Health': 'ആരോഗ്യം',
            'domain.Energy': 'ഊർജ്ജം',
            'domain.Education': 'വിദ്യാഭ്യാസം',
            'domain.Livelihood': 'ഉപജീവനമാർഗ്ഗം',
            'domain.Sustainability': 'സുസ്ഥിരത',
            'status.PROPOSED': 'നിർദ്ദേശിച്ചത്',
            'status.APPROVED': 'അംഗീകരിച്ചത്',
            'status.REJECTED': 'നിരസിച്ചു',
            'status.MATURE': 'പൂർണ്ണമായ',
            'entity_type.NGO': 'എൻജിഒ',
            'entity_type.Social Impact Entity': 'സോഷ്യൽ ഇംപാക്ട് എന്റിറ്റി',
            'entity_type.Academic': 'അക്കാദമിക്',
            'entity_type.Corporate': 'കോർപ്പറേറ്റ്',
            'Organization Name': 'സംഘടനയുടെ പേര്',
            'Entity Type': 'സ്ഥാപന തരം',
            'Location': 'സ്ഥലം',
            'Contact Details': 'ബന്ധപ്പെടാനുള്ള വിശദാംശങ്ങൾ',
            'Solution Name': 'പരിഹാരത്തിന്റെ പേര്',
            'Summary (One Line)': 'സംഗ്രഹം',
            'Description': 'വിവരണം',
            'Domain': 'ഡൊമെയ്ൻ'
        },
        'pa': {
            'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
            'nav.solutions': 'ਹੱਲ',
            'nav.partners': 'ਭਾਈਵਾਲ',
            'nav.tickets': 'ਟਿਕਟਾਂ',
            'nav.users': 'ਉਪਭੋਗਤਾ',
            'nav.reports': 'ਰਿਪੋਰਟਾਂ',
            'nav.login': 'ਲੌਗਇਨ / ਰਜਿਸਟਰ',
            'nav.logout': 'ਲੌਗ ਆਉਟ',
            'common.back': 'ਪਿੱਛੇ',
            'common.save': 'ਸੇਵ ਕਰੋ',
            'common.cancel': 'ਰੱਦ ਕਰੋ',
            'common.view_all': 'ਸਭ ਦੇਖੋ',
            'dashboard.submit_solution': 'ਹੱਲ ਜਮ੍ਹਾਂ ਕਰੋ',
            'dashboard.propose_partner': 'ਭਾਈਵਾਲ ਦਾ ਪ੍ਰਸਤਾਵ',
            'solutions.title': 'ਹੱਲ',
            'partners.title': 'ਭਾਈਵਾਲ',
            'list.search_placeholder': 'ਖੋਜ...',
            'domain.Water': 'ਪਾਣੀ',
            'domain.Health': 'ਸਿਹਤ',
            'domain.Energy': 'ਊਰਜਾ',
            'domain.Education': 'ਸਿੱਖਿਆ',
            'domain.Livelihood': 'ਰੋਜ਼ੀ-ਰੋਟੀ',
            'domain.Sustainability': 'ਸਥਿਰਤਾ',
            'status.PROPOSED': 'ਪ੍ਰਸਤਾਵਿਤ',
            'status.APPROVED': 'ਮਨਜ਼ੂਰ',
            'status.REJECTED': 'ਰੱਦ ਕੀਤਾ',
            'status.MATURE': 'ਪੂਰਾ',
            'entity_type.NGO': 'ਐਨ.ਜੀ.ਓ',
            'entity_type.Social Impact Entity': 'ਸਮਾਜਿਕ ਪ੍ਰਭਾਵ ਸੰਸਥਾ',
            'entity_type.Academic': 'ਵਿੱਦਿਅਕ',
            'entity_type.Corporate': 'ਕਾਰਪੋਰੇਟ',
            'Organization Name': 'ਸੰਸਥਾ ਦਾ ਨਾਮ',
            'Entity Type': 'ਸੰਸਥਾ ਦੀ ਕਿਸਮ',
            'Location': 'ਸਥਾਨ',
            'Contact Details': 'ਸੰਪਰਕ ਵੇਰਵੇ',
            'Solution Name': 'ਹੱਲ ਦਾ ਨਾਮ',
            'Summary (One Line)': 'ਸੰਖੇਪ',
            'Description': 'ਵੇਰਵਾ',
            'Domain': 'ਡੋਮੇਨ'
        }
    } as any;

    const t = (text: string): string => {
        const langDict = DICTIONARY[language];
        const enDict = DICTIONARY['en'];
        // Fallback: Language Specific -> English -> Original Key
        return langDict?.[text] || enDict?.[text] || text;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, direction, t }}>
            <div dir={direction} style={{ minHeight: '100vh', width: '100%' }}>
                {children}
            </div>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export const SUPPORTED_LANGUAGES = LANGUAGES;
